/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.56
 * Generated at: 2020-08-06 04:49:21 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.community;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.kh.baby.community.model.vo.Attachment;
import com.kh.baby.community.model.vo.PageInfo;
import com.kh.baby.community.model.vo.Board;
import java.util.List;
import com.kh.baby.member.model.vo.Member;
import com.kh.baby.member.model.vo.Member;
import com.kh.baby.member.model.vo.General;
import com.kh.baby.member.model.vo.Seller;
import com.kh.baby.member.model.vo.Member;
import com.kh.baby.member.model.vo.General;

public final class free_005flist_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(5);
    _jspx_dependants.put("/WEB-INF/views/community/../common/aside.jsp", Long.valueOf(1596617225429L));
    _jspx_dependants.put("/WEB-INF/views/community/../common/header.jsp", Long.valueOf(1596615410245L));
    _jspx_dependants.put("/WEB-INF/views/mypage/mypage_aside.jsp", Long.valueOf(1596541143522L));
    _jspx_dependants.put("/WEB-INF/views/community/../common/footer.jsp", Long.valueOf(1595827282993L));
    _jspx_dependants.put("/WEB-INF/views/adminPage/adminAside.jsp", Long.valueOf(1596682916010L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("com.kh.baby.member.model.vo.General");
    _jspx_imports_classes.add("com.kh.baby.community.model.vo.Attachment");
    _jspx_imports_classes.add("com.kh.baby.member.model.vo.Seller");
    _jspx_imports_classes.add("com.kh.baby.community.model.vo.PageInfo");
    _jspx_imports_classes.add("com.kh.baby.community.model.vo.Board");
    _jspx_imports_classes.add("com.kh.baby.member.model.vo.Member");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    \r\n");

	PageInfo pInfo = (PageInfo)request.getAttribute("pInfo");
	List<Board> freeList = (List<Board>)request.getAttribute("freeList");
	
	int currentPage = pInfo.getCurrentPage();
	int listCount = pInfo.getListCount();
	int maxPage = pInfo.getMaxPage();
	int startPage = pInfo.getStartPage();
	int endPage = pInfo.getEndPage();
	int boardType = pInfo.getBoardType();
	
	// 페이징바 자리
	int prev = (currentPage - 1)/pInfo.getLimit() * pInfo.getLimit(); // < 버튼
	int next = (currentPage + pInfo.getLimit()-1)/pInfo.getLimit() * pInfo.getLimit() + 1; // > 버튼
	
	String searchKey = request.getParameter("searchKey");
	String searchValue = request.getParameter("searchValue");
	
	String sortType = request.getParameter("sortType");
	
	String url2 = null;
	String searchStr = "";
	
	if(searchKey != null && searchValue != null){
		url2 = request.getContextPath() + "/communitySearch?type=" + boardType + "&cp=";
		searchStr = "&searchKey="+searchKey+"&searchValue="+searchValue;
	}else{
		url2 = request.getContextPath() + "/community/freeList.do?type=" + boardType + "&cp=";
	}
	

	
	String firstPage = url2 + 1 + searchStr;
	String prevPage = url2 + prev + searchStr;
	String nextPage = url2 + next + searchStr;
	String lastPage = url2 + maxPage + searchStr;
	

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("  <meta charset=\"UTF-8\">\r\n");
      out.write("<title>자유게시판(커뮤니티) 글목록 조회</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css\" integrity=\"sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk\" crossorigin=\"anonymous\">\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("\t\r\n");
      out.write("          /* ------------------------------------------------------------------------ */\r\n");
      out.write("          /* content_main 스타일 */\r\n");
      out.write("          #content_main {\r\n");
      out.write("            width: 80%;\r\n");
      out.write("            padding-right: 15px;\r\n");
      out.write("          }\r\n");
      out.write("          \r\n");
      out.write("          /* #content{\r\n");
      out.write("            margin-left: 0;\r\n");
      out.write("            margin-right: 0;\r\n");
      out.write("          } */\r\n");
      out.write("\r\n");
      out.write("          /* ------------------------------------------------------------------- */\r\n");
      out.write("          @font-face { font-family: 'ImcreSoojin'; src: url('https://cdn.jsdelivr.net/gh/projectnoonnu/noonfonts_20-04@2.3/ImcreSoojin.woff') \r\n");
      out.write("          format('woff'); font-weight: normal; font-style: normal; }\r\n");
      out.write("\r\n");
      out.write("          /* 타이틀 */\r\n");
      out.write("          #title{\r\n");
      out.write("            font-family: 'ImcreSoojin';\r\n");
      out.write("            float: left;\r\n");
      out.write("            margin-top: 20px;\r\n");
      out.write("          }\r\n");
      out.write("\r\n");
      out.write("          /* 체크박스, 정렬순서 오른쪽으로 정렬 */\r\n");
      out.write("          #checkboxFloat > *{\r\n");
      out.write("            float: right;\r\n");
      out.write("          }\r\n");
      out.write("          \r\n");
      out.write("          /*분류 필터 오른쪽 정렬*/\r\n");
      out.write("          #filterFloat > *{\r\n");
      out.write("            float: right;\r\n");
      out.write("            display : inline-block;\r\n");
      out.write("          }\r\n");
      out.write("          \r\n");
      out.write("          .filterform {\r\n");
      out.write("          \tfloat : left;\r\n");
      out.write("          }\r\n");
      out.write("          \r\n");
      out.write("\r\n");
      out.write("          /* 페이지 번호 중앙으로 */\r\n");
      out.write("          .pagination {\r\n");
      out.write("            justify-content: center;\r\n");
      out.write("          }\r\n");
      out.write("\r\n");
      out.write("          /* ------------------------------------------------------------------------- */\r\n");
      out.write("          #label-title{\r\n");
      out.write("               color: rgb(56, 190, 243);\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .input-wid{\r\n");
      out.write("                width: 70%;\r\n");
      out.write("            }\r\n");
      out.write("          \r\n");
      out.write("          .modal-body input, .modal-body label, .modal-body textarea{\r\n");
      out.write("            float: left;\r\n");
      out.write("          }\r\n");
      out.write("          \r\n");
      out.write("          /* ---------------------------------분류---------------------------------------*/\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t \r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t.select p {\r\n");
      out.write("\t\t\t\t\t width:100px;background: url(\"bg_selectbox.gif\") no-repeat; font: 12px/20px \"돋움\", \"dotum\"; padding: 0px 14px; border: 1px solid rgb(171, 173, 179); height: 20px; color: rgb(51, 51, 51); overflow: hidden; cursor: pointer; font-size-adjust: none; font-stretch: normal;;margin:0 auto;\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t.select p.on {\r\n");
      out.write("\t\t\t\t\t background-position: right -160px; border: 1px solid rgb(0, 144, 227); color: rgb(0, 144, 227);\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t.select .sub {\r\n");
      out.write("\t\t\t\t\t padding: 6px 0px; border: 1px solid rgb(171, 173, 179); left: 0px; top: 0px; display: none; position: relative; z-index: 10; overflow-x: hidden; overflow-y: scroll; max-height: 168px; background-color: rgb(255, 255, 255);margin:0 auto;\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t.select .sub {\r\n");
      out.write("\t\t\t\t\t width: 100px;\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t.select .sub .optionList {\r\n");
      out.write("\t\t\t\t\t width: 100px; overflow: hidden; float: left; display: inline-block;cursor:pointer;font: 12px/20px \"돋움\", \"dotum\";\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t.select .sub .optionList:hover {\r\n");
      out.write("\t\t\t\t\t background-color: rgb(108, 108, 108);\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t.select .sub .optionList:hover li {\r\n");
      out.write("\t\t\t\t\t color: rgb(255, 255, 255);\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t.select .sub .optionList li {\r\n");
      out.write("\t\t\t\t\t padding: 5px 15px; color: rgb(51, 51, 51);\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t.select .sub .optionList li.name {\r\n");
      out.write("\t\t\t\t\t padding: 5px 0px 5px 15px; width: 210px; float: left; display: inline;\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t.select .sub .optionList li.price {\r\n");
      out.write("\t\t\t\t\t padding: 5px 10px; width: 70px; text-align: right; float: left; display: inline;\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t.select .sub .optionList li.remain {\r\n");
      out.write("\t\t\t\t\t padding: 5px 0px; width: 81px; float: left; display: inline;\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t \r\n");
      out.write("          \r\n");
      out.write("\t\t\t         \r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t\t<div class=\"container-fluid\">\r\n");
      out.write("\t\t\t");
      out.write("\r\n");
      out.write("\r\n");

	Member loginMemberH = (Member)session.getAttribute("loginMember");

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("<head>\r\n");
      out.write("  <meta charset=\"utf-8\">\r\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("  \r\n");
      out.write("  <!-- Bootstrap core CSS -->\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css\">\r\n");
      out.write("\r\n");
      out.write("\t<style>\r\n");
      out.write("\t    /* 전체 사이즈 지정 */\r\n");
      out.write("        .container-fluid {\r\n");
      out.write("            width: 1800px;\r\n");
      out.write("            /* height: 1000px; */\r\n");
      out.write("        }\r\n");
      out.write("        div {\r\n");
      out.write("            /* border: 1px solid black; */\r\n");
      out.write("            text-align: center;\r\n");
      out.write("        }\r\n");
      out.write("        /* header 스타일 */\r\n");
      out.write("        #header {\r\n");
      out.write("        \theight: 160px;\r\n");
      out.write("        }\r\n");
      out.write("        #header img {\r\n");
      out.write("        \theight: 100%;\r\n");
      out.write("        }\r\n");
      out.write("        /* navi 스타일 */\r\n");
      out.write("        .nav {\r\n");
      out.write("            width: 100%;\r\n");
      out.write("        }\r\n");
      out.write("        .nav-item { /* ul > li*/\r\n");
      out.write("            width: 20%;\r\n");
      out.write("            background-color: rgb(186, 234, 253);\r\n");
      out.write("        }\r\n");
      out.write("        .nav li>ul {\r\n");
      out.write("        position: absolute;\r\n");
      out.write("        width: 100%;\r\n");
      out.write("\t\tz-index: 1;\r\n");
      out.write("        background-color: rgb(217, 244, 255);\r\n");
      out.write("\r\n");
      out.write("        list-style-type: none;\r\n");
      out.write("\r\n");
      out.write("        margin: 0;\r\n");
      out.write("        padding: 0;\r\n");
      out.write("\r\n");
      out.write("        opacity: 0;\r\n");
      out.write("        }\r\n");
      out.write("        .nav ul>li>a {\r\n");
      out.write("            opacity: 0;\r\n");
      out.write("        }\r\n");
      out.write("        .nav ul>li {\r\n");
      out.write("            height: 0;\r\n");
      out.write("            line-height: 0;\r\n");
      out.write("        }\r\n");
      out.write("        .nav>li:hover ul, .nav>li:hover ul a {\r\n");
      out.write("            opacity: 1;\r\n");
      out.write("        }\r\n");
      out.write("        .nav li:hover ul li {\r\n");
      out.write("            height: 50px;\r\n");
      out.write("            line-height: 50px;\r\n");
      out.write("        }\r\n");
      out.write("        .nav li ul {\r\n");
      out.write("            transition-duration: 0.4s;\r\n");
      out.write("        }\r\n");
      out.write("   \r\n");
      out.write("\t</style>\r\n");
      out.write("\t<!-- sweetalert : alert창을 꾸밀 수 있게 해주는 라이브러리 https://sweetalert.js.org/ -->\r\n");
      out.write("    <script src=\"https://unpkg.com/sweetalert/dist/sweetalert.min.js\"></script>\r\n");
      out.write("\t\t<script>\r\n");
      out.write("\t\t/**** 이전 페이지에서 전달받은 내용을 alert 창으로 표시하기 ****/\r\n");
      out.write("\t\t");
 
			String msg = (String)(request.getSession().getAttribute("msg"));
			String status = (String)(request.getSession().getAttribute("status"));
			String text = (String)(request.getSession().getAttribute("text"));
		
      out.write("\r\n");
      out.write("\t\t");
 if(msg != null) { 
      out.write("\r\n");
      out.write("\t\t\tswal({\r\n");
      out.write("\t\t\t\ticon : \"");
      out.print(status);
      out.write("\",\r\n");
      out.write("\t\t\t\ttitle : \"");
      out.print(msg);
      out.write("\",\r\n");
      out.write("\t\t\t\ttext : \"");
      out.print(text != null ? text : "");
      out.write("\"\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t");
 // Session에 존재하는 특정 키 값의 속성 제거
			session.removeAttribute("msg"); // session = request.getSession()
			session.removeAttribute("status");
			session.removeAttribute("text");
		} 
      out.write("\r\n");
      out.write("\t\t</script>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("            <div class=\"col-md-12\" id=\"header\">\r\n");
      out.write("              <a href=\"");
      out.print(request.getContextPath());
      out.write("\"><img src=\"");
      out.print(request.getContextPath());
      out.write("/resources/아기.PNG\"></a>\r\n");
      out.write("              <a href=\"");
      out.print(request.getContextPath());
      out.write("\"><img src=\"");
      out.print(request.getContextPath());
      out.write("/resources/로고.png\"></a>\r\n");
      out.write("              <a href=\"");
      out.print(request.getContextPath());
      out.write("\"><img src=\"");
      out.print(request.getContextPath());
      out.write("/resources/아기2.PNG\"></a>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("            <div class=\"col-md-12\">\r\n");
      out.write("                <ul class=\"nav nav-pills nav-justified\">\r\n");
      out.write("                  <li class=\"nav-item\">\r\n");
      out.write("                    <a class=\"nav-link active\" href=\"");
      out.print(request.getContextPath());
      out.write("\">MAIN</a>\r\n");
      out.write("                  </li>\r\n");
      out.write("                  \r\n");
      out.write("                  <li class=\"nav-item\">\r\n");
      out.write("                    <a class=\"nav-link\" href=\"#\">ABOUT</a>\r\n");
      out.write("                  </li>\r\n");
      out.write("                  \r\n");
      out.write("                  <li class=\"nav-item dropdown\">\r\n");
      out.write("                    <a class=\"nav-link dropdown-toggle\" data-toggle=\"dropdown\" href=\"#\" role=\"button\" aria-haspopup=\"true\" aria-expanded=\"false\">INFORMATION</a>\r\n");
      out.write("                      <ul>\r\n");
      out.write("                        <li><a class=\"dropdown-item text-primary\" href=\"");
      out.print(request.getContextPath());
      out.write("/board/hospitalForm.do?type=1&cp=1\">지역별 병원 정보</a></li>\r\n");
      out.write("                        <li><a class=\"dropdown-item text-primary\" href=\"");
      out.print(request.getContextPath());
      out.write("/board/knowledgeForm.do?type=2&cp=1&age=0\">아이 연령대별 상식</a></li>\r\n");
      out.write("                      </ul>\r\n");
      out.write("                  </li>\r\n");
      out.write("                  \r\n");
      out.write("                  <li class=\"nav-item dropdown\">\r\n");
      out.write("                    <a class=\"nav-link dropdown-toggle\" data-toggle=\"dropdown\" href=\"#\" role=\"button\" aria-haspopup=\"true\" aria-expanded=\"false\">COMMUNITY</a>\r\n");
      out.write("                      <ul>\r\n");
      out.write("                        <li><a class=\"dropdown-item text-primary\" href=\"");
      out.print(request.getContextPath());
      out.write("/community/freeList.do?type=3\">자유게시판</a></li>\r\n");
      out.write("                        <li><a class=\"dropdown-item text-primary\" href=\"");
      out.print(request.getContextPath());
      out.write("/community/promoList.do?type=4\">홍보게시판</a></li>\r\n");
      out.write("                      </ul>\r\n");
      out.write("                  </li>\r\n");
      out.write("                  \r\n");
      out.write("                  <li class=\"nav-item dropdown\">\r\n");
      out.write("                    <a class=\"nav-link dropdown-toggle\" data-toggle=\"dropdown\" href=\"");
      out.print(request.getContextPath());
      out.write("/mypage/babyInfoForm.do\" role=\"button\" aria-haspopup=\"true\" aria-expanded=\"false\">MY PAGE</a>\r\n");
      out.write("                    <ul>\r\n");
      out.write("                    \t");
 
                    		String url = request.getContextPath() + "/mypage/babyInfoForm.do?memberNo=";
                    		if(loginMemberH != null) url += loginMemberH.getMemberNo();
                    	
      out.write("\r\n");
      out.write("                    \t");
if(loginMemberH != null) {
      out.write("\r\n");
      out.write("                    \t\t");
if(loginMemberH.getMemberGrade().equals("G")) { 
      out.write("\r\n");
      out.write("\t                        <li><a class=\"dropdown-item text-primary\" href=\"");
      out.print(url);
      out.write("\">우리 아이 정보</a></li>\r\n");
      out.write("\t                        <li><a class=\"dropdown-item text-primary\" href=\"");
      out.print(request.getContextPath());
      out.write("/mypage/babyDiaryForm.do\">육아 일기</a></li>\r\n");
      out.write("\t                        <li><a class=\"dropdown-item text-primary\" href=\"");
      out.print(request.getContextPath());
      out.write("/mypage/myBoardList.do?cp=1\">작성한 글</a></li>\r\n");
      out.write("\t                        <li><a class=\"dropdown-item text-primary\" href=\"");
      out.print(request.getContextPath());
      out.write("/member/updateMemberForm.do\">개인 정보 관리</a></li>\r\n");
      out.write("                        ");
 } else if(loginMemberH.getMemberGrade().equals("S")) { 
      out.write("\r\n");
      out.write("\t                       \t<li><a class=\"dropdown-item text-primary\" href=\"");
      out.print(request.getContextPath());
      out.write("/member/myCompanyInfoForm.do\">우리 회사 정보</a></li>\r\n");
      out.write("\t                        <li><a class=\"dropdown-item text-primary\" href=\"");
      out.print(request.getContextPath());
      out.write("/mypage/myBoardList.do?cp=1\">작성한 글</a></li>\r\n");
      out.write("\t                        <li><a class=\"dropdown-item text-primary\" href=\"");
      out.print(request.getContextPath());
      out.write("/member/updateSellerForm.do\">개인 정보 관리</a></li>\r\n");
      out.write("                        ");
 } else if(loginMemberH.getMemberGrade().equals("A")) { 
      out.write("\r\n");
      out.write("\t                        <li><a class=\"dropdown-item text-primary\" href=\"");
      out.print(request.getContextPath());
      out.write("/adminPage/reportBoard.do\">신고게시판 </a></li>\r\n");
      out.write("\t                        <li><a class=\"dropdown-item text-primary\" href=\"");
      out.print(request.getContextPath());
      out.write("/adminPage/requestBoard.do\">요청게시판</a></li>\r\n");
      out.write("\t                        <li><a class=\"dropdown-item text-primary\" href=\"");
      out.print(request.getContextPath());
      out.write("/adminPage/noticeBoard.do\">공지사항</a></li>\r\n");
      out.write("\t                        <li><a class=\"dropdown-item text-primary\" href=\"");
      out.print(request.getContextPath());
      out.write("/adminPage/memberView.do\">회원 정보 조회</a></li>\r\n");
      out.write("\t                        <li><a class=\"dropdown-item text-primary\" href=\"");
      out.print(request.getContextPath());
      out.write("/adminPage/adminWrite.do\">글쓰기</a></li>\r\n");
      out.write("                        ");
 } }else {
      out.write("\r\n");
      out.write("                        ");
 } 
      out.write("\r\n");
      out.write("                    </ul>\r\n");
      out.write("                  </li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("\t<script>\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t$(\"a[href='#']\").on(\"click\", function(e){\r\n");
      out.write("\t\te.preventeDefault(); \r\n");
      out.write("\t\t// href 속성값이 #인 a태그를 클릭한 경우 기본 이벤트를 제거하는 자바스크립트 코드 입니다.\r\n");
      out.write("\t\t// a태그 기본이벤트 : href 속성에 작성된 주소로 요청보내기\r\n");
      out.write("\t});\r\n");
      out.write("\t</script>\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- Bootstrap core JS -->\r\n");
      out.write("\t<script src=\"https://code.jquery.com/jquery-3.5.1.min.js\"></script>\r\n");
      out.write("\t<script src=\"https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js\" integrity=\"sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("\t<script src=\"https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js\" integrity=\"sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t<div class=\"row\" id=\"content\">\r\n");
      out.write("\t\t  ");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

   Member loginMember = (Member)session.getAttribute("loginMember");
    General loginGeneral = (General)session.getAttribute("loginGeneral");
    Seller loginSeller = (Seller)session.getAttribute("loginSeller");
      
    String babyGender = "";
    if(loginGeneral != null) {
       if(loginGeneral.getKidsHeight() != 0) {
         if(loginGeneral.getKidsGender().equals("f")) {
            babyGender = "여아";
         } else {
            babyGender = "남아";
         }
       }
    }
      
   boolean isSave = false;
   String saveId = "";

   Cookie[] cookies = request.getCookies();

   if (cookies != null) {
      for (Cookie c : cookies) {
         if ("saveId".equals(c.getName())) {
            saveId = c.getValue();
            isSave = true;
         }
      }
   }

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<style>\r\n");
      out.write("/* aside 스타일 */\r\n");
      out.write("\r\n");
      out.write("body{\r\n");
      out.write("\tcursor: default;\r\n");
      out.write("}\r\n");
      out.write("#aside {\r\n");
      out.write("   width: 20%;\r\n");
      out.write("   padding: 0 15px 0 15px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#login{\r\n");
      out.write("   width: 100%\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#login_btn {\r\n");
      out.write("   margin: 5px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".form-signin {\r\n");
      out.write("   background-color: lightgray;\r\n");
      out.write("   width: 100%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".form-signin>* {\r\n");
      out.write("   display: inline-block;\r\n");
      out.write("   margin: 10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#mypage {\r\n");
      out.write("   width: 100%;\r\n");
      out.write("   margin: 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#aside_menu {\r\n");
      out.write("       margin-top: 20px;\r\n");
      out.write("       margin-bottom: 20px;\r\n");
      out.write("       text-align: left;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* 테이블 스타일 지정 */\r\n");
      out.write("#member_info{\r\n");
      out.write("   width: 100%;\r\n");
      out.write("   margin: 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#member_info * {\r\n");
      out.write("   border: 1px solid white;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#member_info th {\r\n");
      out.write("   width: 80px;\r\n");
      out.write("}\r\n");
      out.write("#member_info td {\r\n");
      out.write("   width: 250px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#joinBtn, #findBtn{\r\n");
      out.write("\ttext-decoration: none;\r\n");
      out.write("\tcolor: black;\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write("#img {\r\n");
      out.write("\twidth: 170px;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("   <div id=\"aside\">\r\n");
      out.write("      <div id=\"aside_login\">\r\n");
      out.write("         ");

            if (loginMember == null) {
         
      out.write("\r\n");
      out.write("         <form class=\"form-signin\" method=\"post\"\r\n");
      out.write("            action=\"");
      out.print(request.getContextPath());
      out.write("/member/login.do\">\r\n");
      out.write("            <table>\r\n");
      out.write("               <tr>\r\n");
      out.write("                  <th colspan=\"2\"><h1 class=\"h3 mb-3 font-weight-normal\">로그인</h1></th>\r\n");
      out.write("               </tr>\r\n");
      out.write("               <tr>\r\n");
      out.write("                  <td><input type=\"text\" name=\"inputId\" id=\"inputId\" class=\"form-control\" placeholder=\"아이디\" value=\"");
      out.print(saveId);
      out.write("\" required autofocus></td>\r\n");
      out.write("                  <td rowspan=\"2\">\r\n");
      out.write("                     <button class=\"btn btn-lg btn-primary btn-block\" type=\"submit\" id=\"login_btn\">LOGIN</button>\r\n");
      out.write("                  </td>\r\n");
      out.write("               </tr>\r\n");
      out.write("               <tr>\r\n");
      out.write("                  <td><input type=\"password\" name=\"inputPassword\" id=\"inputPassword\" class=\"form-control\" placeholder=\"비밀번호\" required></td>\r\n");
      out.write("               </tr>\r\n");
      out.write("               <tr>\r\n");
      out.write("                  <td><input type=\"checkbox\" name=\"saveId\" id=\"saveId\" ");
      out.print(isSave ? "checked" : "");
      out.write("><label for=\"saveId\">아이디 저장하기</label></td>\r\n");
      out.write("               </tr>\r\n");
      out.write("            </table>\r\n");
      out.write("\r\n");
      out.write("            <span>저희 홈페이지를<br>찾아주셔서 감사합니다. </span> <br> \r\n");
      out.write("            <a href=\"");
      out.print(request.getContextPath());
      out.write("/member/signUpSelect.do\" id=\"joinBtn\">회원 가입</a> &nbsp;&nbsp;&nbsp;&nbsp; \r\n");
      out.write("            <a href=\"");
      out.print(request.getContextPath());
      out.write("/member/searchSelectForm.do\" id=\"findBtn\">ID/PWD 찾기</a>\r\n");
      out.write("         </form>\r\n");
      out.write("         ");

            } else {
         
      out.write("\r\n");
      out.write("         <div class=\"form-signin\" method=\"post\">\r\n");
      out.write("            <h3>");
      out.print(loginMember.getMemberNickname());
      out.write("님</h3>\r\n");
      out.write("            <a class=\"btn btn-primary\" href=\"");
      out.print(request.getContextPath());
      out.write("/member/logout.do\">Logout</a>\r\n");
      out.write("            ");
 if(loginMember.getMemberGrade().equals("G")) { 
      out.write("\r\n");
      out.write("                  <table id=\"member_info\">\r\n");
      out.write("                     <tr>\r\n");
      out.write("                        <th>주소</th>\r\n");
      out.write("                        <td>\r\n");
      out.write("                           ");
 if(!loginMember.getMemberAddress().equals(",,")) { 
      out.write("\r\n");
      out.write("                              ");
      out.print(loginMember.getMemberAddress());
      out.write("\r\n");
      out.write("                           ");
 } else { 
      out.write("\r\n");
      out.write("                              <a class=\"btn btn-light btn-sm\" href=\"");
      out.print(request.getContextPath());
      out.write("/mypage/updateAddressForm.do\">주소 설정하기</a>\r\n");
      out.write("                           ");
 } 
      out.write("\r\n");
      out.write("                        </td>\r\n");
      out.write("                     </tr>\r\n");
      out.write("      \r\n");
      out.write("                     <tr>\r\n");
      out.write("                        <th rowspan=\"4\">아이 정보  </th>\r\n");
      out.write("                     ");
 if(loginGeneral.getKidsHeight() != 0) {
      out.write("\r\n");
      out.write("                        <td>");
      out.print(loginGeneral.getKidsName());
      out.write("&nbsp;");
      out.print(babyGender);
      out.write("</td>\r\n");
      out.write("                     </tr>\r\n");
      out.write("                     <tr>\r\n");
      out.write("                        <td>생년월일 : ");
      out.print(loginGeneral.getKidsBirth() );
      out.write("</td>\r\n");
      out.write("                     </tr>\r\n");
      out.write("                     <tr>\r\n");
      out.write("                        <td>키 : ");
      out.print(loginGeneral.getKidsHeight() );
      out.write("cm</td>\r\n");
      out.write("                     </tr>\r\n");
      out.write("                     <tr>\r\n");
      out.write("                        <td>몸무게 : ");
      out.print(loginGeneral.getKidsWeight());
      out.write("kg</td>\r\n");
      out.write("                     ");
 } else { 
      out.write("\r\n");
      out.write("                        <td><a class=\"btn btn-light btn-sm\" href=\"");
      out.print(request.getContextPath());
      out.write("/mypage/insertBabyInfoForm.do\">아이 정보 설정하기</a></td>\r\n");
      out.write("                     ");
 } 
      out.write("\r\n");
      out.write("                     </tr>\r\n");
      out.write("                  </table>\r\n");
      out.write("                  ");
 } else if(loginMember.getMemberGrade().equals("S")) { 
      out.write("\r\n");
      out.write("                  <table id=\"member_info\">\r\n");
      out.write("                     <tr>\r\n");
      out.write("                        <th>주소</th>\r\n");
      out.write("                        <td>\r\n");
      out.write("                           ");
 if(!loginMember.getMemberAddress().equals(",,")) { 
      out.write("\r\n");
      out.write("                              ");
      out.print(loginMember.getMemberAddress());
      out.write("\r\n");
      out.write("                           ");
 } else { 
      out.write("\r\n");
      out.write("                              <a class=\"btn btn-light btn-sm\" href=\"");
      out.print(request.getContextPath());
      out.write("/mypage/updateAddressForm.do\">주소 설정하기</a>\r\n");
      out.write("                           ");
 } 
      out.write("\r\n");
      out.write("                        </td>\r\n");
      out.write("                     </tr>\r\n");
      out.write("      \r\n");
      out.write("                     <tr>\r\n");
      out.write("                        <th rowspan=\"2\">회사 정보  </th>\r\n");
      out.write("                     ");
 if(loginSeller != null) {
      out.write("\r\n");
      out.write("                        <td>사업자등록번호 : ");
      out.print(loginSeller.getCompanyNo() );
      out.write("</td>\r\n");
      out.write("                     </tr>\r\n");
      out.write("                     <tr>\r\n");
      out.write("                        <td>회사 전화번호 : ");
      out.print(loginSeller.getCompanyPhone() );
      out.write("</td>\r\n");
      out.write("                     ");
 } else { 
      out.write("\r\n");
      out.write("                        <td><a class=\"btn btn-light btn-sm\" href=\"");
      out.print(request.getContextPath());
      out.write("\">회사 정보 설정하기</a></td>\r\n");
      out.write("                     ");
 } 
      out.write("\r\n");
      out.write("                     </tr>\r\n");
      out.write("                  </table>\r\n");
      out.write("                  ");
 } else {
      out.write("\r\n");
      out.write("                     <img id=\"img\" src=\"");
      out.print(request.getContextPath());
      out.write("/resources/user.png\">\r\n");
      out.write("                  ");
 } 
      out.write("\r\n");
      out.write("         </div>\r\n");
      out.write("         ");
if(loginMember.getMemberGrade().equals("G")) {
      out.write("\r\n");
      out.write("         <button type=\"button\" class=\"btn btn-secondary btn-lg\" id=\"mypage\" onclick=\"location.href='");
      out.print(request.getContextPath());
      out.write("/mypage/myBoardList.do?cp=1';\">MY PAGE</button>\r\n");
      out.write("         ");
} else if(loginMember.getMemberGrade().equals("S")) { 
      out.write("\r\n");
      out.write("         <button type=\"button\" class=\"btn btn-secondary btn-lg\" id=\"mypage\" onclick=\"location.href='");
      out.print(request.getContextPath());
      out.write("/mypage/myBoardList.do?cp=1';\">MY PAGE</button>\r\n");
      out.write("         ");
} else if(loginMember.getMemberGrade().equals("A")) {
      out.write("\r\n");
      out.write("         <button type=\"button\" class=\"btn btn-secondary btn-lg\" id=\"mypage\" onclick=\"location.href='");
      out.print(request.getContextPath());
      out.write("/adminPage/noticeBoard.do';\">MY PAGE</button>\r\n");
      out.write("         ");

            } }
         
      out.write("\r\n");
      out.write("      </div>\r\n");
      out.write("         \r\n");
      out.write("         <div id=\"aside_menu\">\r\n");
      out.write("            ");
 if(loginMember != null){ 
      out.write("\r\n");
      out.write("            ");
if(loginMember.getMemberGrade().equals("A")) {
      out.write("\r\n");
      out.write("            ");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css2?family=Do+Hyeon&family=Gamja+Flower&family=Poor+Story&family=Recursive&family=Sunflower:wght@300;500&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("<style>\r\n");
      out.write(".adminPageSide{\r\n");
      out.write("\tfont-family: Poor Story;\r\n");
      out.write("    font-size: 25px;\r\n");
      out.write("    font-weight: bolder;\r\n");
      out.write("    color:black;\r\n");
      out.write("}\r\n");
      out.write("button{\r\n");
      out.write("  text-align: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("section{\r\n");
      out.write("  display: none;\r\n");
      out.write("  float:left;\r\n");
      out.write("}\r\n");
      out.write(".nav-item{\r\n");
      out.write("width : 100%;\r\n");
      out.write("height : 20%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".adminAside{\r\n");
      out.write("color:black;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<ul class=\"nav flex-column\">\r\n");
      out.write("  <li class=\"nav-item adminPageSide\">\r\n");
      out.write("      <a id=\"report\" class=\"nav-link adminAside\" href=\"");
      out.print(request.getContextPath());
      out.write("/adminPage/reportBoard.do\">신고게시판 <span class=\"badge badge-pill badge-dark\"></span></a>\r\n");
      out.write("    </li>\r\n");
      out.write("  <li class=\"nav-item adminPageSide\">\r\n");
      out.write("    <a id=\"request\" class=\"nav-link adminAside\" href=\"");
      out.print(request.getContextPath());
      out.write("/adminPage/requestBoard.do\">요청게시판 <span class=\"badge badge-pill badge-dark\"></span>  </a>\r\n");
      out.write("  </li>\r\n");
      out.write("  <li class=\"nav-item adminPageSide\">\r\n");
      out.write("    <a class=\"nav-link adminAside\" href=\"");
      out.print(request.getContextPath());
      out.write("/adminPage/noticeBoard.do\">공지사항</a>\r\n");
      out.write("  </li>\r\n");
      out.write("  <li class=\"nav-item adminPageSide\">\r\n");
      out.write("    <a class=\"nav-link adminAside\" href=\"");
      out.print(request.getContextPath());
      out.write("/adminPage/memberView.do\">회원 정보 조회</a>\r\n");
      out.write("  </li>\r\n");
      out.write("  <li class=\"nav-item adminPageSide\">\r\n");
      out.write("    <a class=\"nav-link nav-link dropdown-toggle adminAside\" data-toggle=\"dropdown\" role=\"button\" aria-haspopup=\"true\" aria-expanded=\"false\" width=\"30%\" >글쓰기</a>\r\n");
      out.write("        <div class=\"dropdown-menu\" aria-labelledby=\"navbarDropdown\">\r\n");
      out.write("          <a class=\"dropdown-item\" href=\"");
      out.print(request.getContextPath());
      out.write("/adminPage/adminWrite.do?type=0\">공지사항</a>\r\n");
      out.write("          <a class=\"dropdown-item\" href=\"");
      out.print(request.getContextPath());
      out.write("/adminPage/adminWrite.do?type=1\">병원게시판</a>\r\n");
      out.write("          <a class=\"dropdown-item\" href=\"");
      out.print(request.getContextPath());
      out.write("/adminPage/adminWrite.do?type=2\">상식게시판</a>\r\n");
      out.write("        </div>\r\n");
      out.write("  </li>\r\n");
      out.write("</ul>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("$(function(){\r\n");
      out.write("\t$.ajax({\r\n");
      out.write("\t\turl : \"");
      out.print(request.getContextPath());
      out.write("/adminPage/reportCount.do\",\r\n");
      out.write("\t\tsuccess : function(count){\r\n");
      out.write("\t\t\t$(\"#report > span\").text(count);\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t}, error : function(count){\r\n");
      out.write("\t\t\tconsole.log(\"Ajax 통신 실패\");\r\n");
      out.write("\t\t} \r\n");
      out.write("\t});\t\t\r\n");
      out.write("\t\r\n");
      out.write("\t$.ajax({\r\n");
      out.write("\t\turl : \"");
      out.print(request.getContextPath());
      out.write("/adminPage/requestCount.do\",\r\n");
      out.write("\t\tsuccess : function(count){\r\n");
      out.write("\t\t\t$(\"#request > span\").text(count);\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t}, error : function(count){\r\n");
      out.write("\t\t\tconsole.log(\"Ajax 통신 실패\");\r\n");
      out.write("\t\t} \r\n");
      out.write("\t});\t\t\r\n");
      out.write("});\r\n");
      out.write("</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("            ");
} else { 
      out.write("\r\n");
      out.write("            ");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	Member mploginMember = (Member)session.getAttribute("loginMember");
  General mploginGeneral = (General)session.getAttribute("loginGeneral"); 

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<style>\r\n");
      out.write("/* -------------------------------------------- */\r\n");
      out.write("\r\n");
      out.write("    .dropdown-toggle::after {\r\n");
      out.write("      display: block;\r\n");
      out.write("      position: absolute;\r\n");
      out.write("      top: 50%;\r\n");
      out.write("      right: 20px;\r\n");
      out.write("      transform: translateY(-50%);\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .asideCategory\r\n");
      out.write("    {\r\n");
      out.write("        text-decoration: none; color: black;\r\n");
      out.write("        display: block;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .asideCategory:hover{\r\n");
      out.write("        text-decoration: none; color: black; font-weight: bold;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("\t#aside_menu li>a{\r\n");
      out.write("\t\twidth: 100%;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t        <ul class=\"list-group\">\r\n");
      out.write("\t        ");
if(mploginMember.getMemberGrade().equals("G")) { 
      out.write("\r\n");
      out.write("\t        \t\t");
if(mploginGeneral.getKidsHeight()==0 && mploginGeneral.getKidsWeight()==0){ 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<li class=\"list-group-item\" id=\"atag1\"><a href=\"");
      out.print(request.getContextPath());
      out.write("/mypage/insertBabyInfoForm.do\" class=\"asideCategory\">우리 아이 정보</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t");
}else{ 
      out.write("\r\n");
      out.write("\t\t\t       \t\t<li class=\"list-group-item\" id=\"atag1\"><a href=\"");
      out.print(request.getContextPath());
      out.write("/mypage/babyInfoForm.do\" class=\"asideCategory\">우리 아이 정보</a></li>\r\n");
      out.write("\t\t\t       \t\t<li class=\"list-group-item\" id=\"atag2\" ><a href=\"");
      out.print(request.getContextPath());
      out.write("/mypage/babyDiaryForm.do?cp=1\" class=\"asideCategory\"\">육아일기</a></li>\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t");
 }
      out.write("\r\n");
      out.write("\t       \t");
} else { 
      out.write("\r\n");
      out.write("\t       \t\t<li class=\"list-group-item\" id=\"atag1\"><a href=\"");
      out.print(request.getContextPath());
      out.write("/member/myCompanyInfoForm.do\" class=\"asideCategory\">우리 회사 정보</a></li>\r\n");
      out.write("\t       \t");
 } 
      out.write("\r\n");
      out.write("\t       \t\t<li class=\"list-group-item\" id=\"atag3\"><a href=\"");
      out.print(request.getContextPath());
      out.write("/mypage/myBoardList.do?cp=1\" class=\"asideCategory\" >작성한 글</a></li>\r\n");
      out.write("\t\r\n");
      out.write("\t       \t\t<li class=\"list-group-item\" id=\"atag4\">\r\n");
      out.write("\t           \t\t<a href=\"#pageSubmenu\" data-toggle=\"collapse\" aria-expanded=\"false\" aria-haspopup=\"true\" class=\"asideCategory\">개인 정보 관리</a>\r\n");
      out.write("\t           \t\t<ul class=\"collapse list-unstyled\" id=\"pageSubmenu\">\r\n");
      out.write("\t               \t");
if(mploginMember.getMemberGrade().equals("G")) { 
      out.write("\r\n");
      out.write("\t               \t\t<li >\r\n");
      out.write("\t                   \t\t<a href=\"");
      out.print(request.getContextPath());
      out.write("/member/updateMemberForm.do\" class=\"asideCategory\"> - 개인 정보 수정</a> \r\n");
      out.write("\t               \t\t</li>\r\n");
      out.write("\t               \t");
} else { 
      out.write("       \r\n");
      out.write("\t               \t\t<li >\r\n");
      out.write("\t                   \t\t<a href=\"");
      out.print(request.getContextPath());
      out.write("/member/updateSellerForm.do\" class=\"asideCategory\"> - 회사 정보 수정</a> \r\n");
      out.write("\t               \t\t</li>\r\n");
      out.write("\t               \t");
 } 
      out.write("\r\n");
      out.write("\t               \t\t<li>\r\n");
      out.write("\t                   \t\t<a href=\"");
      out.print(request.getContextPath());
      out.write("/member/signOutForm.do\" class=\"asideCategory\"> - 회원 탈퇴</a>\r\n");
      out.write("\t               \t\t</li>\r\n");
      out.write("\t               \t\t<li>\r\n");
      out.write("\t                   \t\t<a href=\"");
      out.print(request.getContextPath());
      out.write("/mypage/replacePwdForm.do\" class=\"asideCategory\"> - 비밀번호 변경</a>\r\n");
      out.write("\t               \t\t</li>\r\n");
      out.write("\t           \t\t</ul>\r\n");
      out.write("\t       \t\t</li>\r\n");
      out.write("\t     \t</ul>\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\r\n");
      out.write("\t\t$(\"#atag1, #atag2, #atag3, #atag4\").on({\"mouseenter\" : function(){\r\n");
      out.write("\t\t\t$(this).css(\"backgroundColor\", \"rgb(186, 234, 253)\");\r\n");
      out.write("\t\t}, \"mouseleave\" : function(){\r\n");
      out.write("\t\t\t$(this).css(\"backgroundColor\", \"rgb(0, 0, 0, 0)\");\r\n");
      out.write("\t\t}});\r\n");
      out.write("\t\r\n");
      out.write("\t</script>\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("            ");
   } 
      out.write("\r\n");
      out.write("            ");
 } 
      out.write("\r\n");
      out.write("      </div>\r\n");
      out.write("   </div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\t\t  \r\n");
      out.write("\t\t  \r\n");
      out.write("               <div id=\"content_main\">\r\n");
      out.write("                  <div class=\"row\">\r\n");
      out.write("                    <div class=\"col-md-12\">\r\n");
      out.write("                        <h2 id=\"title\">커뮤니티(자유게시판)</h2>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("             \r\n");
      out.write("                  <!-- 상단 분류 SELECT -->\r\n");
      out.write("           ");
      out.write("\r\n");
      out.write("                \r\n");
      out.write("              <div class=\"row padding\">\r\n");
      out.write("              <div class=\"col-md-12\" id=\"filterFloat\">\r\n");
      out.write("                <form action=\"");
      out.print(request.getContextPath() );
      out.write("/community/freeSort.do\" method=\"get\" id=\"freeSort\">\r\n");
      out.write("                <input type=\"hidden\" name=\"type\" value=\"");
      out.print(boardType);
      out.write("\">\r\n");
      out.write("                <input type=\"hidden\" name=\"cp\" value=\"1\">\r\n");
      out.write("                  <select name=\"sortType\" class=\"form-control filterform\" style=\"width:100px;\" display: inline-block;>\r\n");
      out.write("                      <option value=\"전체보기\">전체보기</option>\r\n");
      out.write("                      <option value=\"나눔\">나눔</option>\r\n");
      out.write("                      <option value=\"수다\">수다</option>\r\n");
      out.write("                      <option value=\"질문\">질문</option>\r\n");
      out.write("                  </select> \r\n");
      out.write("                  <button class=\"form-control btn btn-primary filterform\" style=\"width:100px;\" id=\"filterbtn\">적용</button>\r\n");
      out.write("              </form>\r\n");
      out.write("             \r\n");
      out.write("          </div>\r\n");
      out.write("              </div> \r\n");
      out.write("              \r\n");
      out.write("   \r\n");
      out.write(" \r\n");
      out.write("                \r\n");
      out.write("\r\n");
      out.write("       \r\n");
      out.write("                <!-- 게시판 목록 -->\r\n");
      out.write("                <div class=\"row\">\r\n");
      out.write("                    <div class=\"col-md-12\">\r\n");
      out.write("                        <table class=\"table table-sm\" id=\"list-table\">\r\n");
      out.write("                            <thead>\r\n");
      out.write("                              <tr>\r\n");
      out.write("                                <th scope=\"col\">글번호</th>\r\n");
      out.write("                                <th scope=\"col\">분류</th>\r\n");
      out.write("                                <th scope=\"col\">제목</th>\r\n");
      out.write("                                <th scope=\"col\">작성자</th>\r\n");
      out.write("                                <th scope=\"col\">조회수</th>\r\n");
      out.write("                                <th scope=\"col\">좋아요</th>\r\n");
      out.write("                                <th scope=\"col\">작성일</th>\r\n");
      out.write("                              </tr>\r\n");
      out.write("                            </thead>\r\n");
      out.write("                            <tbody>\r\n");
      out.write("                            \r\n");
      out.write("                            ");
if (freeList.isEmpty()){ 
      out.write("\r\n");
      out.write("                            \t<tr><td colspan=\"6\">존재하는 게시글이 없습니다.</td>\r\n");
      out.write("                            \r\n");
      out.write("                               ");
 } else {  
      out.write("\r\n");
      out.write("                               \r\n");
      out.write("                               \r\n");
      out.write("\t              \t\t\t");
 for (Board board : freeList) { 
      out.write("\r\n");
      out.write("\t              \t\t\t\r\n");
      out.write("\t              \t\t\t");
if(board.getBoardNotice().equals("Y")) {
      out.write("\r\n");
      out.write("                            \t\r\n");
      out.write("                            \t<th scope=\"row\">");
      out.print(board.getBoardNo() );
      out.write("</th>\r\n");
      out.write("                                <td>");
      out.print(board.getCategoryName() );
      out.write("</td>\r\n");
      out.write("                                <td>");
      out.print(board.getBoardTitle() );
      out.write("</td>\r\n");
      out.write("                                <td>");
      out.print(board.getMemberName() );
      out.write("</td>\r\n");
      out.write("                                <td>");
      out.print(board.getReadCount() );
      out.write("</td>\r\n");
      out.write("                                <td>");
      out.print(board.getBoardLike() );
      out.write("</td>\r\n");
      out.write("                                <td>");
      out.print(board.getBoardCreateDate() );
      out.write("</td>\r\n");
      out.write("                              </tr>\t\r\n");
      out.write("                            \t\t\t\r\n");
      out.write("                            \t");
} else {
      out.write("\t\t\r\n");
      out.write("                                <th scope=\"row\">");
      out.print(board.getBoardNo() );
      out.write("</th>\r\n");
      out.write("                                <td>");
      out.print(board.getCategoryName() );
      out.write("</td>\r\n");
      out.write("                                <td>");
      out.print(board.getBoardTitle() );
      out.write("</td>\r\n");
      out.write("                                <td>");
      out.print(board.getMemberName() );
      out.write("</td>\r\n");
      out.write("                                <td>");
      out.print(board.getReadCount() );
      out.write("</td>\r\n");
      out.write("                                <td>");
      out.print(board.getBoardLike() );
      out.write("</td>\r\n");
      out.write("                                <td>");
      out.print(board.getBoardCreateDate() );
      out.write("</td>\r\n");
      out.write("                              </tr>\r\n");
      out.write("                              \r\n");
      out.write("                             \t\t");
 } 
      out.write("\t\r\n");
      out.write("                           \t\t");
 } 
      out.write("\r\n");
      out.write("\t            \t\t \t\t\t  ");
 } 
      out.write("\r\n");
      out.write("                            </tbody>\r\n");
      out.write("                          </table>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                \r\n");
      out.write("                  ");
      out.write("\r\n");
      out.write("\t      \t");
if(loginMember != null && (loginMember.getMemberGrade().equals("G") ||loginMember.getMemberGrade().equals("A")) ){ 
      out.write("\r\n");
      out.write("    \r\n");
      out.write("                <!-- 글쓰기 버튼 -->\r\n");
      out.write("                <div class=\"row\">\r\n");
      out.write("                    <div class=\"col-md-12\">\r\n");
      out.write("                      <button type=\"button\"  id=\"requestBtn\" class=\"btn btn-primary btn-sm float-right\" onclick=\"location.href ='freeInsertForm.do?type=");
      out.print(boardType);
      out.write("'\">글쓰기</button>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("    \r\n");
      out.write("    \t\t\t");
 } 
      out.write("\r\n");
      out.write("    \r\n");
      out.write("    \t");
 if (sortType ==null ) { 
      out.write("\r\n");
      out.write("                <!-- 페이지 번호 -->\r\n");
      out.write("                   ");
 if(!freeList.isEmpty()) { 
      out.write("\r\n");
      out.write("         \t\t\t\t<div style=\"clear: both\">\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"pagination\">\r\n");
      out.write("\t\t\t\t\t\t\t");
if(currentPage > pInfo.getLimit()) { 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<!-- 맨 처음 페이지로 이동 [<<] -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<a class=\"page-link\" href=\"");
      out.print(request.getContextPath());
      out.write("/community/freeList.do?type=");
      out.print(boardType);
      out.write("&cp=1\">&lt;&lt;</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<!-- 이전 순번의 페이징바로 이동 [<] -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<a class=\"page-link\" href=\"");
      out.print(request.getContextPath());
      out.write("/community/freeList.do?type=");
      out.print(boardType);
      out.write("&cp=");
      out.print(prev);
      out.write("\">&lt;</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t");
} 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<!-- 5개의 페이지 목록 -->\r\n");
      out.write("\t\t\t\t\t\t\t");
for(int p=startPage; p<=endPage; p++) { 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");
if(p == currentPage) { 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<li><a class=\"page-link\">");
      out.print(p);
      out.write("</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");
} else { 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<li><a class=\"page-link\" href=\"");
      out.print(request.getContextPath());
      out.write("/community/freeList.do?type=");
      out.print(boardType);
      out.write("&cp=");
      out.print(p);
      out.write('"');
      out.write('>');
      out.print(p);
      out.write("</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");
} 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t");
} 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t");
if(next <= maxPage) { 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<!-- 다음 페이징바 [>] -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<a class=\"page-link\" href=\"");
      out.print(request.getContextPath());
      out.write("/community/freeList.do?type=");
      out.print(boardType);
      out.write("&cp=");
      out.print(next);
      out.write("\">&gt;</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<!-- 마지막 페이지로 이동 [>>] -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<a class=\"page-link\" href=\"");
      out.print(request.getContextPath());
      out.write("/community/freeList.do?type=");
      out.print(boardType);
      out.write("&cp=");
      out.print(maxPage);
      out.write("\">&gt;&gt;</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t");
} 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</ul>\t        \r\n");
      out.write("\t        </div>\r\n");
      out.write("\t        ");
 } } else { 
      out.write("\r\n");
      out.write("\t        \r\n");
      out.write("\t        \t <!-- 페이지 번호 -->\r\n");
      out.write("                   ");
 if(!freeList.isEmpty()) { 
      out.write("\r\n");
      out.write("         \t\t\t\t<div style=\"clear: both\">\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"pagination\">\r\n");
      out.write("\t\t\t\t\t\t\t");
if(currentPage > pInfo.getLimit()) { 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<!-- 맨 처음 페이지로 이동 [<<] -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<a class=\"page-link\" href=\"");
      out.print(request.getContextPath());
      out.write("/community/freeList.do?type=");
      out.print(boardType);
      out.write("&cp=1&sortType=");
      out.print(sortType);
      out.write("\">&lt;&lt;</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<!-- 이전 순번의 페이징바로 이동 [<] -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<a class=\"page-link\" href=\"");
      out.print(request.getContextPath());
      out.write("/community/freeList.do?type=");
      out.print(boardType);
      out.write("&cp=");
      out.print(prev);
      out.write("&sortType=");
      out.print(sortType);
      out.write("\">&lt;</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t");
} 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<!-- 5개의 페이지 목록 -->\r\n");
      out.write("\t\t\t\t\t\t\t");
for(int p=startPage; p<=endPage; p++) { 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");
if(p == currentPage) { 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<li><a class=\"page-link\">");
      out.print(p);
      out.write("</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");
} else { 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<li><a class=\"page-link\" href=\"");
      out.print(request.getContextPath());
      out.write("/community/freeList.do?type=");
      out.print(boardType);
      out.write("&cp=");
      out.print(p);
      out.write("&sortType=");
      out.print(sortType);
      out.write('"');
      out.write('>');
      out.print(p);
      out.write("</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");
} 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t");
} 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t");
if(next <= maxPage) { 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<!-- 다음 페이징바 [>] -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<a class=\"page-link\" href=\"");
      out.print(request.getContextPath());
      out.write("/community/freeList.do?type=");
      out.print(boardType);
      out.write("&cp=");
      out.print(next);
      out.write("&sortType=");
      out.print(sortType);
      out.write("\">&gt;</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<!-- 마지막 페이지로 이동 [>>] -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<a class=\"page-link\" href=\"");
      out.print(request.getContextPath());
      out.write("/community/freeList.do?type=");
      out.print(boardType);
      out.write("&cp=");
      out.print(maxPage);
      out.write("&sortType=");
      out.print(sortType);
      out.write("\">&gt;&gt;</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t");
} 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</ul>\t        \r\n");
      out.write("\t        </div>\r\n");
      out.write("\t        ");
 } 
      out.write("\r\n");
      out.write("\t        \r\n");
      out.write("\t        ");
 } 
      out.write("\r\n");
      out.write("    \r\n");
      out.write("               <!-- 검색창 -->\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("              <div class=\"col-md-12\">\r\n");
      out.write("                <form action=\"");
      out.print(request.getContextPath() );
      out.write("/communitySearch\" method=\"get\" class=\"text-center\" id=\"searchForm\">\r\n");
      out.write("                <input type=\"hidden\" name=\"type\" value=\"");
      out.print(boardType);
      out.write("\">\r\n");
      out.write("                <input type=\"hidden\" name=\"cp\" value=\"");
      out.print(currentPage );
      out.write("\">\r\n");
      out.write("                  <select name=\"searchKey\" class=\"form-control\" style=\"width:100px; display: inline-block;\">\r\n");
      out.write("                      <option value=\"title\">글제목</option>\r\n");
      out.write("                      <option value=\"content\">내용</option>\r\n");
      out.write("                      <option value=\"all\">제목+내용</option>\r\n");
      out.write("                  </select>\r\n");
      out.write("                  <input type=\"text\" name=\"searchValue\" class=\"form-control\" style=\"width:25%; display: inline-block;\" placeholder=\"검색키워드를 입력해주세요.\">\r\n");
      out.write("                  <button class=\"form-control btn btn-primary\" style=\"width:100px; display: inline-block;\" id=\"seachbtn\">검색</button>\r\n");
      out.write("              </form>\r\n");
      out.write("              </div>\r\n");
      out.write("          </div>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("           \r\n");
      out.write("\r\n");
      out.write("\t\t");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<style>\r\n");
      out.write("\t#footer {\r\n");
      out.write("\t\twidth: 100%;\r\n");
      out.write("\t\tbackground-color: lightgray;\r\n");
      out.write("\t\tpadding: 20px;\r\n");
      out.write("\t\tmargin-top : 15px;\r\n");
      out.write("\t}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div class=\"row\">\r\n");
      out.write("\t\t<div class=\"col-md-12\">\r\n");
      out.write("\t\t  <p id=\"footer\">KH정보교육원 A클래스 - 세미 프로젝트 육아를도와조(5조) 슬기로운 육아생활</p>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("       \r\n");
      out.write("\t\t\r\n");
      out.write("    <script>\r\n");
      out.write("\t\t// 게시글 상세보기 기능 (jquery를 통해 작업)\r\n");
      out.write("\t\t$(function(){\r\n");
      out.write("\t\t\t$(\"#list-table td\").click(function(){\r\n");
      out.write("\t\t\t\tvar boardNo = $(this).parent().children().eq(0).text();\r\n");
      out.write("\t\t\t\tconsole.log(boardNo);\r\n");
      out.write("\t\t\t\tlocation.href = \"");
      out.print(request.getContextPath());
      out.write("/community/freeView.do?type=");
      out.print(boardType);
      out.write("&cp=");
      out.print(currentPage);
      out.write("&no=\"+boardNo;\r\n");
      out.write("\t\t\t}).mouseenter(function(){\r\n");
      out.write("\t\t\t\t$(this).parent().css(\"cursor\", \"pointer\");\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t// 검색 기능\r\n");
      out.write("\t\t$(function(){\r\n");
      out.write("\t\t\tvar searchKey = \"");
      out.print( searchKey );
      out.write("\";\r\n");
      out.write("\t\t\tvar searchValue = \"");
      out.print( searchValue );
      out.write("\";\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tif(searchKey != \"null\" && searchValue != \"null\"){\r\n");
      out.write("\t\t\t\t$.each($(\"select[name=searchKey] > option\"), function(index, item){\r\n");
      out.write("\t\t\t\t\tif($(item).val() == searchKey){\r\n");
      out.write("\t\t\t\t\t\t$(item).prop(\"selected\",\"true\");\r\n");
      out.write("\t\t\t\t\t} \r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t$(\"input[name=searchValue]\").val(searchValue);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t// 분류 필터 기능\r\n");
      out.write("\t\t$(function(){\r\n");
      out.write("\t\t\tvar sortType = \"");
      out.print(sortType);
      out.write("\";\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tif(sortType != \"null\" ){\r\n");
      out.write("\t\t\t\t$.each($(\"select[name=sortType] > option\"), function(index, item){\r\n");
      out.write("\t\t\t\t\tif($(item).val() == sortType){\r\n");
      out.write("\t\t\t\t\t\t$(item).prop(\"selected\",\"true\");\r\n");
      out.write("\t\t\t\t\t} \r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t}); \r\n");
      out.write("\t\t\r\n");
      out.write("\r\n");
      out.write("\t\t$(document).ready(function(){  \r\n");
      out.write("\t\t  $(\".select p\").click(function(){    \r\n");
      out.write("\t\t   $(\".select p\").addClass(\"on\");  \r\n");
      out.write("\t\t   $(\".select .sub\").slideToggle(\"fast\");   \r\n");
      out.write("\t\t   \r\n");
      out.write("\t\t   \t$(\".select .sub\").click(function(){\r\n");
      out.write("\t\t   \t\t\tconsole.log(\"클릭\");\r\n");
      out.write("\t\t   \t\t\t\r\n");
      out.write("\t\t   \t});\r\n");
      out.write("\r\n");
      out.write("\t\t  });\r\n");
      out.write("\t\t \r\n");
      out.write("\t\t  $(\".select .sub\").mouseleave(function() {\r\n");
      out.write("\t\t   $(\".select p\").removeClass(\"on\"); \r\n");
      out.write("\t\t  $(this).hide();\r\n");
      out.write("\t\t });\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t// 글자수 제한\r\n");
      out.write("        $(\"textarea\").on(\"input\", function() {\r\n");
      out.write("\t           \r\n");
      out.write("\t           var inputLength = $(this).val().length;\r\n");
      out.write("\t     \r\n");
      out.write("\t           $(\"#counter\").text(inputLength);\r\n");
      out.write("\t     \r\n");
      out.write("\t           if(inputLength - 150 < 0) {\r\n");
      out.write("\t             $(\"#counter\").css(\"color\", \"black\");\r\n");
      out.write("\t           } else {\r\n");
      out.write("\t             $(\"#counter\").css(\"color\", \"red\");\r\n");
      out.write("\t           }\r\n");
      out.write("\t           \r\n");
      out.write("\t           if(inputLength > 150){\r\n");
      out.write("\t        \t   alert(\"최대 150자까지 입력 가능합니다.\");\t        \t   \r\n");
      out.write("\t           }\r\n");
      out.write("\t         });\r\n");
      out.write("\t\t\r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("\t</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
