/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.56
 * Generated at: 2020-08-06 03:11:43 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.community;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.kh.baby.community.model.vo.Attachment;
import java.util.ArrayList;
import com.kh.baby.community.model.vo.Board;
import com.kh.baby.member.model.vo.Member;
import com.kh.baby.member.model.vo.Member;
import com.kh.baby.member.model.vo.General;
import com.kh.baby.member.model.vo.Seller;
import com.kh.baby.member.model.vo.Member;
import com.kh.baby.member.model.vo.General;
import com.kh.baby.community.model.vo.Board;
import com.kh.baby.member.model.vo.Member;

public final class promo_005fview_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(6);
    _jspx_dependants.put("/WEB-INF/views/community/../common/aside.jsp", Long.valueOf(1596617225429L));
    _jspx_dependants.put("/WEB-INF/views/community/../common/header.jsp", Long.valueOf(1596615410245L));
    _jspx_dependants.put("/WEB-INF/views/mypage/mypage_aside.jsp", Long.valueOf(1596541143522L));
    _jspx_dependants.put("/WEB-INF/views/community/../community/community_reply.jsp", Long.valueOf(1596611103015L));
    _jspx_dependants.put("/WEB-INF/views/community/../common/footer.jsp", Long.valueOf(1595827282993L));
    _jspx_dependants.put("/WEB-INF/views/adminPage/adminAside.jsp", Long.valueOf(1596682916010L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.kh.baby.member.model.vo.General");
    _jspx_imports_classes.add("com.kh.baby.community.model.vo.Attachment");
    _jspx_imports_classes.add("com.kh.baby.member.model.vo.Seller");
    _jspx_imports_classes.add("com.kh.baby.community.model.vo.Board");
    _jspx_imports_classes.add("com.kh.baby.member.model.vo.Member");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
 
	Board board = (Board)request.getAttribute("board");
	ArrayList<Attachment> fList = (ArrayList<Attachment>)request.getAttribute("fList");
	String cp = request.getParameter("cp");
	String type = request.getParameter("type");
	int boardNo = board.getBoardNo();
	String memberId = board.getMemberId();

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>홍보게시판 상세조회</title>\r\n");
      out.write("<style>\r\n");
      out.write("#content-area{ margin-bottom:200px;}\r\n");
      out.write("\t#board-content{ padding-bottom:150px;}\r\n");
      out.write("\t\r\n");
      out.write("\thtml{width:100%;height:100%;}\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("\t#board-imgArea img { display:block; }\r\n");
      out.write("\t\r\n");
      out.write("\t  /* 팝업 레이어 */\r\n");
      out.write("   .idSelect {\r\n");
      out.write("      cursor: pointer;\r\n");
      out.write("   }\r\n");
      out.write("   \r\n");
      out.write("   .popupLayer {\r\n");
      out.write("      position: absolute;\r\n");
      out.write("      display: none;\r\n");
      out.write("      background-color: #ffffff;\r\n");
      out.write("      border: solid 2px #d0d0d0;\r\n");
      out.write("      width: 250px;\r\n");
      out.write("      height: 250px;\r\n");
      out.write("      padding: 10px;\r\n");
      out.write("   }\r\n");
      out.write("   .popupLayer div:nth-of-type(1) {\r\n");
      out.write("      position: absolute;\r\n");
      out.write("      top: 5px;\r\n");
      out.write("      right: 5px\r\n");
      out.write("   }\r\n");
      out.write("   \r\n");
      out.write("\t#board-content {\r\n");
      out.write("\t\t\tmargin-top: 30px;\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t.boardImgArea img{\r\n");
      out.write("\t\twidth : 100%;\r\n");
      out.write("\t\theight: 100%;\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tmax-width : 300px;\r\n");
      out.write("\t\tmax-height: 300px;\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tmargin : auto;\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("  \r\n");
      out.write("\r\n");
      out.write("\t\t.promo_area{\r\n");
      out.write("                width:100%;\r\n");
      out.write("                height: 300px;\r\n");
      out.write("                float:left;\r\n");
      out.write("                margin-top : 30px;\r\n");
      out.write("            }\r\n");
      out.write("            \r\n");
      out.write("\t\t#updateBtn{\r\n");
      out.write("\t\ttext-decoration: \"none\";\r\n");
      out.write("\t\tcolor: black }\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t#promo_thum{\r\n");
      out.write("\t\t\twidth: 50%;\r\n");
      out.write("\t\t\theight: 100%;\r\n");
      out.write("\t\t\tfloat:left;\r\n");
      out.write("\t\t\ttext-align: center;\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t#promo_detail{\r\n");
      out.write("\t\t\twidth: 50%;\r\n");
      out.write("\t\t\theight: 100%;\r\n");
      out.write("\t\t\tfloat:left;\r\n");
      out.write("\t\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t#promo_detail td {\r\n");
      out.write("\t\t\theight: 40px;\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t/*댓글*/\r\n");
      out.write("\t\t.replyWrite>table {\r\n");
      out.write("\t\t\twidth: 90%;\r\n");
      out.write("\t\t\tmargin-top : 100px;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t#replyContentArea {\r\n");
      out.write("\t\t\twidth: 90%;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t#replyContentArea>textarea {\r\n");
      out.write("\t\t\tresize: none;\r\n");
      out.write("\t\t\twidth: 100%;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t#replyBtnArea {\r\n");
      out.write("\t\t\twidth: 100px;\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t.rWriter {\r\n");
      out.write("\t\t\tdisplay : inline-block;\r\n");
      out.write("\t\t\tmargin-right: 30px;\r\n");
      out.write("\t\t\tvertical-align: top;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t.rDate {\r\n");
      out.write("\t\t\tdisplay : inline-block;\r\n");
      out.write("\t\t\tfont-size: 0.5em;\r\n");
      out.write("\t\t\tcolor: gray;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t#replyListArea {\r\n");
      out.write("\t\t\tlist-style-type: none;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t.rContent, .btnArea{\r\n");
      out.write("\t\t\tdisplay: inline-block;\r\n");
      out.write("\t\t\tbox-sizing: border-box;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t.rContent {\r\n");
      out.write("\t\t\theight: 100%;\r\n");
      out.write("\t\t\twidth : 84.5%;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t.btnArea {\r\n");
      out.write("\t\t\theight: 100%;\r\n");
      out.write("\t\t\twidth : 15%;\r\n");
      out.write("\t\t\ttext-align: right;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t#deleteBtn{\r\n");
      out.write("    \tcursor : pointer;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write(" \r\n");
      out.write("\t     \r\n");
      out.write("\t </style>\r\n");
      out.write("\t \r\n");
      out.write("\t   <!-- sweetalert : alert창을 꾸밀 수 있게 해주는 라이브러리 https://sweetalert.js.org/ -->\r\n");
      out.write("  <script src=\"https://unpkg.com/sweetalert/dist/sweetalert.min.js\"></script>\r\n");
      out.write("\t \r\n");
      out.write("  <!-- Bootstrap core CSS -->\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css\">\r\n");
      out.write("\t \r\n");
      out.write("\t \r\n");
      out.write("\t</script>\r\n");
      out.write("\t \r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"container-fluid\">\r\n");
      out.write("\t\t");
      out.write("\r\n");
      out.write("\r\n");

	Member loginMemberH = (Member)session.getAttribute("loginMember");

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("<head>\r\n");
      out.write("  <meta charset=\"utf-8\">\r\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("  \r\n");
      out.write("  <!-- Bootstrap core CSS -->\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css\">\r\n");
      out.write("\r\n");
      out.write("\t<style>\r\n");
      out.write("\t    /* 전체 사이즈 지정 */\r\n");
      out.write("        .container-fluid {\r\n");
      out.write("            width: 1800px;\r\n");
      out.write("            /* height: 1000px; */\r\n");
      out.write("        }\r\n");
      out.write("        div {\r\n");
      out.write("            /* border: 1px solid black; */\r\n");
      out.write("            text-align: center;\r\n");
      out.write("        }\r\n");
      out.write("        /* header 스타일 */\r\n");
      out.write("        #header {\r\n");
      out.write("        \theight: 160px;\r\n");
      out.write("        }\r\n");
      out.write("        #header img {\r\n");
      out.write("        \theight: 100%;\r\n");
      out.write("        }\r\n");
      out.write("        /* navi 스타일 */\r\n");
      out.write("        .nav {\r\n");
      out.write("            width: 100%;\r\n");
      out.write("        }\r\n");
      out.write("        .nav-item { /* ul > li*/\r\n");
      out.write("            width: 20%;\r\n");
      out.write("            background-color: rgb(186, 234, 253);\r\n");
      out.write("        }\r\n");
      out.write("        .nav li>ul {\r\n");
      out.write("        position: absolute;\r\n");
      out.write("        width: 100%;\r\n");
      out.write("\t\tz-index: 1;\r\n");
      out.write("        background-color: rgb(217, 244, 255);\r\n");
      out.write("\r\n");
      out.write("        list-style-type: none;\r\n");
      out.write("\r\n");
      out.write("        margin: 0;\r\n");
      out.write("        padding: 0;\r\n");
      out.write("\r\n");
      out.write("        opacity: 0;\r\n");
      out.write("        }\r\n");
      out.write("        .nav ul>li>a {\r\n");
      out.write("            opacity: 0;\r\n");
      out.write("        }\r\n");
      out.write("        .nav ul>li {\r\n");
      out.write("            height: 0;\r\n");
      out.write("            line-height: 0;\r\n");
      out.write("        }\r\n");
      out.write("        .nav>li:hover ul, .nav>li:hover ul a {\r\n");
      out.write("            opacity: 1;\r\n");
      out.write("        }\r\n");
      out.write("        .nav li:hover ul li {\r\n");
      out.write("            height: 50px;\r\n");
      out.write("            line-height: 50px;\r\n");
      out.write("        }\r\n");
      out.write("        .nav li ul {\r\n");
      out.write("            transition-duration: 0.4s;\r\n");
      out.write("        }\r\n");
      out.write("   \r\n");
      out.write("\t</style>\r\n");
      out.write("\t<!-- sweetalert : alert창을 꾸밀 수 있게 해주는 라이브러리 https://sweetalert.js.org/ -->\r\n");
      out.write("    <script src=\"https://unpkg.com/sweetalert/dist/sweetalert.min.js\"></script>\r\n");
      out.write("\t\t<script>\r\n");
      out.write("\t\t/**** 이전 페이지에서 전달받은 내용을 alert 창으로 표시하기 ****/\r\n");
      out.write("\t\t");
 
			String msg = (String)(request.getSession().getAttribute("msg"));
			String status = (String)(request.getSession().getAttribute("status"));
			String text = (String)(request.getSession().getAttribute("text"));
		
      out.write("\r\n");
      out.write("\t\t");
 if(msg != null) { 
      out.write("\r\n");
      out.write("\t\t\tswal({\r\n");
      out.write("\t\t\t\ticon : \"");
      out.print(status);
      out.write("\",\r\n");
      out.write("\t\t\t\ttitle : \"");
      out.print(msg);
      out.write("\",\r\n");
      out.write("\t\t\t\ttext : \"");
      out.print(text != null ? text : "");
      out.write("\"\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t");
 // Session에 존재하는 특정 키 값의 속성 제거
			session.removeAttribute("msg"); // session = request.getSession()
			session.removeAttribute("status");
			session.removeAttribute("text");
		} 
      out.write("\r\n");
      out.write("\t\t</script>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("            <div class=\"col-md-12\" id=\"header\">\r\n");
      out.write("              <a href=\"");
      out.print(request.getContextPath());
      out.write("\"><img src=\"");
      out.print(request.getContextPath());
      out.write("/resources/아기.PNG\"></a>\r\n");
      out.write("              <a href=\"");
      out.print(request.getContextPath());
      out.write("\"><img src=\"");
      out.print(request.getContextPath());
      out.write("/resources/로고.png\"></a>\r\n");
      out.write("              <a href=\"");
      out.print(request.getContextPath());
      out.write("\"><img src=\"");
      out.print(request.getContextPath());
      out.write("/resources/아기2.PNG\"></a>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("            <div class=\"col-md-12\">\r\n");
      out.write("                <ul class=\"nav nav-pills nav-justified\">\r\n");
      out.write("                  <li class=\"nav-item\">\r\n");
      out.write("                    <a class=\"nav-link active\" href=\"");
      out.print(request.getContextPath());
      out.write("\">MAIN</a>\r\n");
      out.write("                  </li>\r\n");
      out.write("                  \r\n");
      out.write("                  <li class=\"nav-item\">\r\n");
      out.write("                    <a class=\"nav-link\" href=\"#\">ABOUT</a>\r\n");
      out.write("                  </li>\r\n");
      out.write("                  \r\n");
      out.write("                  <li class=\"nav-item dropdown\">\r\n");
      out.write("                    <a class=\"nav-link dropdown-toggle\" data-toggle=\"dropdown\" href=\"#\" role=\"button\" aria-haspopup=\"true\" aria-expanded=\"false\">INFORMATION</a>\r\n");
      out.write("                      <ul>\r\n");
      out.write("                        <li><a class=\"dropdown-item text-primary\" href=\"");
      out.print(request.getContextPath());
      out.write("/board/hospitalForm.do?type=1&cp=1\">지역별 병원 정보</a></li>\r\n");
      out.write("                        <li><a class=\"dropdown-item text-primary\" href=\"");
      out.print(request.getContextPath());
      out.write("/board/knowledgeForm.do?type=2&cp=1&age=0\">아이 연령대별 상식</a></li>\r\n");
      out.write("                      </ul>\r\n");
      out.write("                  </li>\r\n");
      out.write("                  \r\n");
      out.write("                  <li class=\"nav-item dropdown\">\r\n");
      out.write("                    <a class=\"nav-link dropdown-toggle\" data-toggle=\"dropdown\" href=\"#\" role=\"button\" aria-haspopup=\"true\" aria-expanded=\"false\">COMMUNITY</a>\r\n");
      out.write("                      <ul>\r\n");
      out.write("                        <li><a class=\"dropdown-item text-primary\" href=\"");
      out.print(request.getContextPath());
      out.write("/community/freeList.do?type=3\">자유게시판</a></li>\r\n");
      out.write("                        <li><a class=\"dropdown-item text-primary\" href=\"");
      out.print(request.getContextPath());
      out.write("/community/promoList.do?type=4\">홍보게시판</a></li>\r\n");
      out.write("                      </ul>\r\n");
      out.write("                  </li>\r\n");
      out.write("                  \r\n");
      out.write("                  <li class=\"nav-item dropdown\">\r\n");
      out.write("                    <a class=\"nav-link dropdown-toggle\" data-toggle=\"dropdown\" href=\"");
      out.print(request.getContextPath());
      out.write("/mypage/babyInfoForm.do\" role=\"button\" aria-haspopup=\"true\" aria-expanded=\"false\">MY PAGE</a>\r\n");
      out.write("                    <ul>\r\n");
      out.write("                    \t");
 
                    		String url = request.getContextPath() + "/mypage/babyInfoForm.do?memberNo=";
                    		if(loginMemberH != null) url += loginMemberH.getMemberNo();
                    	
      out.write("\r\n");
      out.write("                    \t");
if(loginMemberH != null) {
      out.write("\r\n");
      out.write("                    \t\t");
if(loginMemberH.getMemberGrade().equals("G")) { 
      out.write("\r\n");
      out.write("\t                        <li><a class=\"dropdown-item text-primary\" href=\"");
      out.print(url);
      out.write("\">우리 아이 정보</a></li>\r\n");
      out.write("\t                        <li><a class=\"dropdown-item text-primary\" href=\"");
      out.print(request.getContextPath());
      out.write("/mypage/babyDiaryForm.do\">육아 일기</a></li>\r\n");
      out.write("\t                        <li><a class=\"dropdown-item text-primary\" href=\"");
      out.print(request.getContextPath());
      out.write("/mypage/myBoardList.do?cp=1\">작성한 글</a></li>\r\n");
      out.write("\t                        <li><a class=\"dropdown-item text-primary\" href=\"");
      out.print(request.getContextPath());
      out.write("/member/updateMemberForm.do\">개인 정보 관리</a></li>\r\n");
      out.write("                        ");
 } else if(loginMemberH.getMemberGrade().equals("S")) { 
      out.write("\r\n");
      out.write("\t                       \t<li><a class=\"dropdown-item text-primary\" href=\"");
      out.print(request.getContextPath());
      out.write("/member/myCompanyInfoForm.do\">우리 회사 정보</a></li>\r\n");
      out.write("\t                        <li><a class=\"dropdown-item text-primary\" href=\"");
      out.print(request.getContextPath());
      out.write("/mypage/myBoardList.do?cp=1\">작성한 글</a></li>\r\n");
      out.write("\t                        <li><a class=\"dropdown-item text-primary\" href=\"");
      out.print(request.getContextPath());
      out.write("/member/updateSellerForm.do\">개인 정보 관리</a></li>\r\n");
      out.write("                        ");
 } else if(loginMemberH.getMemberGrade().equals("A")) { 
      out.write("\r\n");
      out.write("\t                        <li><a class=\"dropdown-item text-primary\" href=\"");
      out.print(request.getContextPath());
      out.write("/adminPage/reportBoard.do\">신고게시판 </a></li>\r\n");
      out.write("\t                        <li><a class=\"dropdown-item text-primary\" href=\"");
      out.print(request.getContextPath());
      out.write("/adminPage/requestBoard.do\">요청게시판</a></li>\r\n");
      out.write("\t                        <li><a class=\"dropdown-item text-primary\" href=\"");
      out.print(request.getContextPath());
      out.write("/adminPage/noticeBoard.do\">공지사항</a></li>\r\n");
      out.write("\t                        <li><a class=\"dropdown-item text-primary\" href=\"");
      out.print(request.getContextPath());
      out.write("/adminPage/memberView.do\">회원 정보 조회</a></li>\r\n");
      out.write("\t                        <li><a class=\"dropdown-item text-primary\" href=\"");
      out.print(request.getContextPath());
      out.write("/adminPage/adminWrite.do\">글쓰기</a></li>\r\n");
      out.write("                        ");
 } }else {
      out.write("\r\n");
      out.write("                        ");
 } 
      out.write("\r\n");
      out.write("                    </ul>\r\n");
      out.write("                  </li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("\t<script>\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t$(\"a[href='#']\").on(\"click\", function(e){\r\n");
      out.write("\t\te.preventeDefault(); \r\n");
      out.write("\t\t// href 속성값이 #인 a태그를 클릭한 경우 기본 이벤트를 제거하는 자바스크립트 코드 입니다.\r\n");
      out.write("\t\t// a태그 기본이벤트 : href 속성에 작성된 주소로 요청보내기\r\n");
      out.write("\t});\r\n");
      out.write("\t</script>\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- Bootstrap core JS -->\r\n");
      out.write("\t<script src=\"https://code.jquery.com/jquery-3.5.1.min.js\"></script>\r\n");
      out.write("\t<script src=\"https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js\" integrity=\"sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("\t<script src=\"https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js\" integrity=\"sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
      out.write(" \r\n");
      out.write("\t\r\n");
      out.write("\t\t<div class=\"row\" id=\"content\">\r\n");
      out.write("\t  ");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

   Member loginMember = (Member)session.getAttribute("loginMember");
    General loginGeneral = (General)session.getAttribute("loginGeneral");
    Seller loginSeller = (Seller)session.getAttribute("loginSeller");
      
    String babyGender = "";
    if(loginGeneral != null) {
       if(loginGeneral.getKidsHeight() != 0) {
         if(loginGeneral.getKidsGender().equals("f")) {
            babyGender = "여아";
         } else {
            babyGender = "남아";
         }
       }
    }
      
   boolean isSave = false;
   String saveId = "";

   Cookie[] cookies = request.getCookies();

   if (cookies != null) {
      for (Cookie c : cookies) {
         if ("saveId".equals(c.getName())) {
            saveId = c.getValue();
            isSave = true;
         }
      }
   }

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<style>\r\n");
      out.write("/* aside 스타일 */\r\n");
      out.write("\r\n");
      out.write("body{\r\n");
      out.write("\tcursor: default;\r\n");
      out.write("}\r\n");
      out.write("#aside {\r\n");
      out.write("   width: 20%;\r\n");
      out.write("   padding: 0 15px 0 15px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#login{\r\n");
      out.write("   width: 100%\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#login_btn {\r\n");
      out.write("   margin: 5px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".form-signin {\r\n");
      out.write("   background-color: lightgray;\r\n");
      out.write("   width: 100%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".form-signin>* {\r\n");
      out.write("   display: inline-block;\r\n");
      out.write("   margin: 10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#mypage {\r\n");
      out.write("   width: 100%;\r\n");
      out.write("   margin: 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#aside_menu {\r\n");
      out.write("       margin-top: 20px;\r\n");
      out.write("       margin-bottom: 20px;\r\n");
      out.write("       text-align: left;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* 테이블 스타일 지정 */\r\n");
      out.write("#member_info{\r\n");
      out.write("   width: 100%;\r\n");
      out.write("   margin: 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#member_info * {\r\n");
      out.write("   border: 1px solid white;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#member_info th {\r\n");
      out.write("   width: 80px;\r\n");
      out.write("}\r\n");
      out.write("#member_info td {\r\n");
      out.write("   width: 250px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#joinBtn, #findBtn{\r\n");
      out.write("\ttext-decoration: none;\r\n");
      out.write("\tcolor: black;\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write("#img {\r\n");
      out.write("\twidth: 170px;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("   <div id=\"aside\">\r\n");
      out.write("      <div id=\"aside_login\">\r\n");
      out.write("         ");

            if (loginMember == null) {
         
      out.write("\r\n");
      out.write("         <form class=\"form-signin\" method=\"post\"\r\n");
      out.write("            action=\"");
      out.print(request.getContextPath());
      out.write("/member/login.do\">\r\n");
      out.write("            <table>\r\n");
      out.write("               <tr>\r\n");
      out.write("                  <th colspan=\"2\"><h1 class=\"h3 mb-3 font-weight-normal\">로그인</h1></th>\r\n");
      out.write("               </tr>\r\n");
      out.write("               <tr>\r\n");
      out.write("                  <td><input type=\"text\" name=\"inputId\" id=\"inputId\" class=\"form-control\" placeholder=\"아이디\" value=\"");
      out.print(saveId);
      out.write("\" required autofocus></td>\r\n");
      out.write("                  <td rowspan=\"2\">\r\n");
      out.write("                     <button class=\"btn btn-lg btn-primary btn-block\" type=\"submit\" id=\"login_btn\">LOGIN</button>\r\n");
      out.write("                  </td>\r\n");
      out.write("               </tr>\r\n");
      out.write("               <tr>\r\n");
      out.write("                  <td><input type=\"password\" name=\"inputPassword\" id=\"inputPassword\" class=\"form-control\" placeholder=\"비밀번호\" required></td>\r\n");
      out.write("               </tr>\r\n");
      out.write("               <tr>\r\n");
      out.write("                  <td><input type=\"checkbox\" name=\"saveId\" id=\"saveId\" ");
      out.print(isSave ? "checked" : "");
      out.write("><label for=\"saveId\">아이디 저장하기</label></td>\r\n");
      out.write("               </tr>\r\n");
      out.write("            </table>\r\n");
      out.write("\r\n");
      out.write("            <span>저희 홈페이지를<br>찾아주셔서 감사합니다. </span> <br> \r\n");
      out.write("            <a href=\"");
      out.print(request.getContextPath());
      out.write("/member/signUpSelect.do\" id=\"joinBtn\">회원 가입</a> &nbsp;&nbsp;&nbsp;&nbsp; \r\n");
      out.write("            <a href=\"");
      out.print(request.getContextPath());
      out.write("/member/searchSelectForm.do\" id=\"findBtn\">ID/PWD 찾기</a>\r\n");
      out.write("         </form>\r\n");
      out.write("         ");

            } else {
         
      out.write("\r\n");
      out.write("         <div class=\"form-signin\" method=\"post\">\r\n");
      out.write("            <h3>");
      out.print(loginMember.getMemberNickname());
      out.write("님</h3>\r\n");
      out.write("            <a class=\"btn btn-primary\" href=\"");
      out.print(request.getContextPath());
      out.write("/member/logout.do\">Logout</a>\r\n");
      out.write("            ");
 if(loginMember.getMemberGrade().equals("G")) { 
      out.write("\r\n");
      out.write("                  <table id=\"member_info\">\r\n");
      out.write("                     <tr>\r\n");
      out.write("                        <th>주소</th>\r\n");
      out.write("                        <td>\r\n");
      out.write("                           ");
 if(!loginMember.getMemberAddress().equals(",,")) { 
      out.write("\r\n");
      out.write("                              ");
      out.print(loginMember.getMemberAddress());
      out.write("\r\n");
      out.write("                           ");
 } else { 
      out.write("\r\n");
      out.write("                              <a class=\"btn btn-light btn-sm\" href=\"");
      out.print(request.getContextPath());
      out.write("/mypage/updateAddressForm.do\">주소 설정하기</a>\r\n");
      out.write("                           ");
 } 
      out.write("\r\n");
      out.write("                        </td>\r\n");
      out.write("                     </tr>\r\n");
      out.write("      \r\n");
      out.write("                     <tr>\r\n");
      out.write("                        <th rowspan=\"4\">아이 정보  </th>\r\n");
      out.write("                     ");
 if(loginGeneral.getKidsHeight() != 0) {
      out.write("\r\n");
      out.write("                        <td>");
      out.print(loginGeneral.getKidsName());
      out.write("&nbsp;");
      out.print(babyGender);
      out.write("</td>\r\n");
      out.write("                     </tr>\r\n");
      out.write("                     <tr>\r\n");
      out.write("                        <td>생년월일 : ");
      out.print(loginGeneral.getKidsBirth() );
      out.write("</td>\r\n");
      out.write("                     </tr>\r\n");
      out.write("                     <tr>\r\n");
      out.write("                        <td>키 : ");
      out.print(loginGeneral.getKidsHeight() );
      out.write("cm</td>\r\n");
      out.write("                     </tr>\r\n");
      out.write("                     <tr>\r\n");
      out.write("                        <td>몸무게 : ");
      out.print(loginGeneral.getKidsWeight());
      out.write("kg</td>\r\n");
      out.write("                     ");
 } else { 
      out.write("\r\n");
      out.write("                        <td><a class=\"btn btn-light btn-sm\" href=\"");
      out.print(request.getContextPath());
      out.write("/mypage/insertBabyInfoForm.do\">아이 정보 설정하기</a></td>\r\n");
      out.write("                     ");
 } 
      out.write("\r\n");
      out.write("                     </tr>\r\n");
      out.write("                  </table>\r\n");
      out.write("                  ");
 } else if(loginMember.getMemberGrade().equals("S")) { 
      out.write("\r\n");
      out.write("                  <table id=\"member_info\">\r\n");
      out.write("                     <tr>\r\n");
      out.write("                        <th>주소</th>\r\n");
      out.write("                        <td>\r\n");
      out.write("                           ");
 if(!loginMember.getMemberAddress().equals(",,")) { 
      out.write("\r\n");
      out.write("                              ");
      out.print(loginMember.getMemberAddress());
      out.write("\r\n");
      out.write("                           ");
 } else { 
      out.write("\r\n");
      out.write("                              <a class=\"btn btn-light btn-sm\" href=\"");
      out.print(request.getContextPath());
      out.write("/mypage/updateAddressForm.do\">주소 설정하기</a>\r\n");
      out.write("                           ");
 } 
      out.write("\r\n");
      out.write("                        </td>\r\n");
      out.write("                     </tr>\r\n");
      out.write("      \r\n");
      out.write("                     <tr>\r\n");
      out.write("                        <th rowspan=\"2\">회사 정보  </th>\r\n");
      out.write("                     ");
 if(loginSeller != null) {
      out.write("\r\n");
      out.write("                        <td>사업자등록번호 : ");
      out.print(loginSeller.getCompanyNo() );
      out.write("</td>\r\n");
      out.write("                     </tr>\r\n");
      out.write("                     <tr>\r\n");
      out.write("                        <td>회사 전화번호 : ");
      out.print(loginSeller.getCompanyPhone() );
      out.write("</td>\r\n");
      out.write("                     ");
 } else { 
      out.write("\r\n");
      out.write("                        <td><a class=\"btn btn-light btn-sm\" href=\"");
      out.print(request.getContextPath());
      out.write("\">회사 정보 설정하기</a></td>\r\n");
      out.write("                     ");
 } 
      out.write("\r\n");
      out.write("                     </tr>\r\n");
      out.write("                  </table>\r\n");
      out.write("                  ");
 } else {
      out.write("\r\n");
      out.write("                     <img id=\"img\" src=\"");
      out.print(request.getContextPath());
      out.write("/resources/user.png\">\r\n");
      out.write("                  ");
 } 
      out.write("\r\n");
      out.write("         </div>\r\n");
      out.write("         ");
if(loginMember.getMemberGrade().equals("G")) {
      out.write("\r\n");
      out.write("         <button type=\"button\" class=\"btn btn-secondary btn-lg\" id=\"mypage\" onclick=\"location.href='");
      out.print(request.getContextPath());
      out.write("/mypage/myBoardList.do?cp=1';\">MY PAGE</button>\r\n");
      out.write("         ");
} else if(loginMember.getMemberGrade().equals("S")) { 
      out.write("\r\n");
      out.write("         <button type=\"button\" class=\"btn btn-secondary btn-lg\" id=\"mypage\" onclick=\"location.href='");
      out.print(request.getContextPath());
      out.write("/mypage/myBoardList.do?cp=1';\">MY PAGE</button>\r\n");
      out.write("         ");
} else if(loginMember.getMemberGrade().equals("A")) {
      out.write("\r\n");
      out.write("         <button type=\"button\" class=\"btn btn-secondary btn-lg\" id=\"mypage\" onclick=\"location.href='");
      out.print(request.getContextPath());
      out.write("/adminPage/noticeBoard.do';\">MY PAGE</button>\r\n");
      out.write("         ");

            } }
         
      out.write("\r\n");
      out.write("      </div>\r\n");
      out.write("         \r\n");
      out.write("         <div id=\"aside_menu\">\r\n");
      out.write("            ");
 if(loginMember != null){ 
      out.write("\r\n");
      out.write("            ");
if(loginMember.getMemberGrade().equals("A")) {
      out.write("\r\n");
      out.write("            ");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css2?family=Do+Hyeon&family=Gamja+Flower&family=Poor+Story&family=Recursive&family=Sunflower:wght@300;500&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("<style>\r\n");
      out.write(".adminPageSide{\r\n");
      out.write("\tfont-family: Poor Story;\r\n");
      out.write("    font-size: 25px;\r\n");
      out.write("    font-weight: bolder;\r\n");
      out.write("    color:black;\r\n");
      out.write("}\r\n");
      out.write("button{\r\n");
      out.write("  text-align: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("section{\r\n");
      out.write("  display: none;\r\n");
      out.write("  float:left;\r\n");
      out.write("}\r\n");
      out.write(".nav-item{\r\n");
      out.write("width : 100%;\r\n");
      out.write("height : 20%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".adminAside{\r\n");
      out.write("color:black;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<ul class=\"nav flex-column\">\r\n");
      out.write("  <li class=\"nav-item adminPageSide\">\r\n");
      out.write("      <a id=\"report\" class=\"nav-link adminAside\" href=\"");
      out.print(request.getContextPath());
      out.write("/adminPage/reportBoard.do\">신고게시판 <span class=\"badge badge-pill badge-dark\"></span></a>\r\n");
      out.write("    </li>\r\n");
      out.write("  <li class=\"nav-item adminPageSide\">\r\n");
      out.write("    <a id=\"request\" class=\"nav-link adminAside\" href=\"");
      out.print(request.getContextPath());
      out.write("/adminPage/requestBoard.do\">요청게시판 <span class=\"badge badge-pill badge-dark\"></span>  </a>\r\n");
      out.write("  </li>\r\n");
      out.write("  <li class=\"nav-item adminPageSide\">\r\n");
      out.write("    <a class=\"nav-link adminAside\" href=\"");
      out.print(request.getContextPath());
      out.write("/adminPage/noticeBoard.do\">공지사항</a>\r\n");
      out.write("  </li>\r\n");
      out.write("  <li class=\"nav-item adminPageSide\">\r\n");
      out.write("    <a class=\"nav-link adminAside\" href=\"");
      out.print(request.getContextPath());
      out.write("/adminPage/memberView.do\">회원 정보 조회</a>\r\n");
      out.write("  </li>\r\n");
      out.write("  <li class=\"nav-item adminPageSide\">\r\n");
      out.write("    <a class=\"nav-link nav-link dropdown-toggle adminAside\" data-toggle=\"dropdown\" role=\"button\" aria-haspopup=\"true\" aria-expanded=\"false\" width=\"30%\" >글쓰기</a>\r\n");
      out.write("        <div class=\"dropdown-menu\" aria-labelledby=\"navbarDropdown\">\r\n");
      out.write("          <a class=\"dropdown-item\" href=\"");
      out.print(request.getContextPath());
      out.write("/adminPage/adminWrite.do?type=0\">공지사항</a>\r\n");
      out.write("          <a class=\"dropdown-item\" href=\"");
      out.print(request.getContextPath());
      out.write("/adminPage/adminWrite.do?type=1\">병원게시판</a>\r\n");
      out.write("          <a class=\"dropdown-item\" href=\"");
      out.print(request.getContextPath());
      out.write("/adminPage/adminWrite.do?type=2\">상식게시판</a>\r\n");
      out.write("        </div>\r\n");
      out.write("  </li>\r\n");
      out.write("</ul>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("$(function(){\r\n");
      out.write("\t$.ajax({\r\n");
      out.write("\t\turl : \"");
      out.print(request.getContextPath());
      out.write("/adminPage/reportCount.do\",\r\n");
      out.write("\t\tsuccess : function(count){\r\n");
      out.write("\t\t\t$(\"#report > span\").text(count);\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t}, error : function(count){\r\n");
      out.write("\t\t\tconsole.log(\"Ajax 통신 실패\");\r\n");
      out.write("\t\t} \r\n");
      out.write("\t});\t\t\r\n");
      out.write("\t\r\n");
      out.write("\t$.ajax({\r\n");
      out.write("\t\turl : \"");
      out.print(request.getContextPath());
      out.write("/adminPage/requestCount.do\",\r\n");
      out.write("\t\tsuccess : function(count){\r\n");
      out.write("\t\t\t$(\"#request > span\").text(count);\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t}, error : function(count){\r\n");
      out.write("\t\t\tconsole.log(\"Ajax 통신 실패\");\r\n");
      out.write("\t\t} \r\n");
      out.write("\t});\t\t\r\n");
      out.write("});\r\n");
      out.write("</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("            ");
} else { 
      out.write("\r\n");
      out.write("            ");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	Member mploginMember = (Member)session.getAttribute("loginMember");
  General mploginGeneral = (General)session.getAttribute("loginGeneral"); 

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<style>\r\n");
      out.write("/* -------------------------------------------- */\r\n");
      out.write("\r\n");
      out.write("    .dropdown-toggle::after {\r\n");
      out.write("      display: block;\r\n");
      out.write("      position: absolute;\r\n");
      out.write("      top: 50%;\r\n");
      out.write("      right: 20px;\r\n");
      out.write("      transform: translateY(-50%);\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .asideCategory\r\n");
      out.write("    {\r\n");
      out.write("        text-decoration: none; color: black;\r\n");
      out.write("        display: block;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .asideCategory:hover{\r\n");
      out.write("        text-decoration: none; color: black; font-weight: bold;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("\t#aside_menu li>a{\r\n");
      out.write("\t\twidth: 100%;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t        <ul class=\"list-group\">\r\n");
      out.write("\t        ");
if(mploginMember.getMemberGrade().equals("G")) { 
      out.write("\r\n");
      out.write("\t        \t\t");
if(mploginGeneral.getKidsHeight()==0 && mploginGeneral.getKidsWeight()==0){ 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<li class=\"list-group-item\" id=\"atag1\"><a href=\"");
      out.print(request.getContextPath());
      out.write("/mypage/insertBabyInfoForm.do\" class=\"asideCategory\">우리 아이 정보</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t");
}else{ 
      out.write("\r\n");
      out.write("\t\t\t       \t\t<li class=\"list-group-item\" id=\"atag1\"><a href=\"");
      out.print(request.getContextPath());
      out.write("/mypage/babyInfoForm.do\" class=\"asideCategory\">우리 아이 정보</a></li>\r\n");
      out.write("\t\t\t       \t\t<li class=\"list-group-item\" id=\"atag2\" ><a href=\"");
      out.print(request.getContextPath());
      out.write("/mypage/babyDiaryForm.do?cp=1\" class=\"asideCategory\"\">육아일기</a></li>\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t");
 }
      out.write("\r\n");
      out.write("\t       \t");
} else { 
      out.write("\r\n");
      out.write("\t       \t\t<li class=\"list-group-item\" id=\"atag1\"><a href=\"");
      out.print(request.getContextPath());
      out.write("/member/myCompanyInfoForm.do\" class=\"asideCategory\">우리 회사 정보</a></li>\r\n");
      out.write("\t       \t");
 } 
      out.write("\r\n");
      out.write("\t       \t\t<li class=\"list-group-item\" id=\"atag3\"><a href=\"");
      out.print(request.getContextPath());
      out.write("/mypage/myBoardList.do?cp=1\" class=\"asideCategory\" >작성한 글</a></li>\r\n");
      out.write("\t\r\n");
      out.write("\t       \t\t<li class=\"list-group-item\" id=\"atag4\">\r\n");
      out.write("\t           \t\t<a href=\"#pageSubmenu\" data-toggle=\"collapse\" aria-expanded=\"false\" aria-haspopup=\"true\" class=\"asideCategory\">개인 정보 관리</a>\r\n");
      out.write("\t           \t\t<ul class=\"collapse list-unstyled\" id=\"pageSubmenu\">\r\n");
      out.write("\t               \t");
if(mploginMember.getMemberGrade().equals("G")) { 
      out.write("\r\n");
      out.write("\t               \t\t<li >\r\n");
      out.write("\t                   \t\t<a href=\"");
      out.print(request.getContextPath());
      out.write("/member/updateMemberForm.do\" class=\"asideCategory\"> - 개인 정보 수정</a> \r\n");
      out.write("\t               \t\t</li>\r\n");
      out.write("\t               \t");
} else { 
      out.write("       \r\n");
      out.write("\t               \t\t<li >\r\n");
      out.write("\t                   \t\t<a href=\"");
      out.print(request.getContextPath());
      out.write("/member/updateSellerForm.do\" class=\"asideCategory\"> - 회사 정보 수정</a> \r\n");
      out.write("\t               \t\t</li>\r\n");
      out.write("\t               \t");
 } 
      out.write("\r\n");
      out.write("\t               \t\t<li>\r\n");
      out.write("\t                   \t\t<a href=\"");
      out.print(request.getContextPath());
      out.write("/member/signOutForm.do\" class=\"asideCategory\"> - 회원 탈퇴</a>\r\n");
      out.write("\t               \t\t</li>\r\n");
      out.write("\t               \t\t<li>\r\n");
      out.write("\t                   \t\t<a href=\"");
      out.print(request.getContextPath());
      out.write("/mypage/replacePwdForm.do\" class=\"asideCategory\"> - 비밀번호 변경</a>\r\n");
      out.write("\t               \t\t</li>\r\n");
      out.write("\t           \t\t</ul>\r\n");
      out.write("\t       \t\t</li>\r\n");
      out.write("\t     \t</ul>\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\r\n");
      out.write("\t\t$(\"#atag1, #atag2, #atag3, #atag4\").on({\"mouseenter\" : function(){\r\n");
      out.write("\t\t\t$(this).css(\"backgroundColor\", \"rgb(186, 234, 253)\");\r\n");
      out.write("\t\t}, \"mouseleave\" : function(){\r\n");
      out.write("\t\t\t$(this).css(\"backgroundColor\", \"rgb(0, 0, 0, 0)\");\r\n");
      out.write("\t\t}});\r\n");
      out.write("\t\r\n");
      out.write("\t</script>\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("            ");
   } 
      out.write("\r\n");
      out.write("            ");
 } 
      out.write("\r\n");
      out.write("      </div>\r\n");
      out.write("   </div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- Bootstrap core JS -->\r\n");
      out.write("\t<script src=\"https://code.jquery.com/jquery-3.5.1.min.js\"></script>\r\n");
      out.write("\t<script src=\"https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js\" integrity=\"sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("\t<script src=\"https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js\" integrity=\"sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"container my-5\">\r\n");
      out.write("\r\n");
      out.write("\t\t<div id=\"content-area\">\r\n");
      out.write("\t\t\t\r\n");
      out.write("\r\n");
      out.write("            <!-- Title -->\r\n");
      out.write("      \r\n");
      out.write("\t\t\t<p>\r\n");
      out.write("\t\t\t<span class=\"float-left\"> \t<h3>홍보게시판</h3>\t</span>\r\n");
      out.write("\t\t\t</p>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!-- Writer -->\r\n");
      out.write("\t\t\t<p class=\"lead\">\r\n");
      out.write("\t\t\t<span class=\"float-left\"> \t작성자 : <a class=\"idSelect\">");
      out.print(board.getMemberName() );
      out.write("</a>\r\n");
      out.write("                &nbsp;| &nbsp;\r\n");
      out.write("           \t\t");
      out.print(board.getBoardCreateDate() );
      out.write(" </span>\r\n");
      out.write("\t\t\t\t <span class=\"float-right\">조회수 <pr>");
      out.print(board.getReadCount() );
      out.write("</pr> </span>\r\n");
      out.write("\t\t\t</p>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<hr>\r\n");
      out.write("\t\t\t<br>\r\n");
      out.write("\t\t\t<p>\r\n");
      out.write("\t\t\t\t<span class=\"float-left\">  좋아요 <pr>");
      out.print(board.getBoardLike() );
      out.write("</pr> </span>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("  \t");
if(loginMember != null  && loginMember.getMemberGrade().equals("S")  && loginMember.getMemberId().equals(memberId)) {
      out.write("\t\t\t\t \r\n");
      out.write("  \t\t <span class=\"float-right\" id=\"deleteBtn\">\r\n");
      out.write("\t\t\t\t 삭제</span>\r\n");
      out.write("\t\t\t\t <span class=\"float-right\">|&nbsp;&nbsp;</span>\r\n");
      out.write("\t\t\t\t \r\n");
      out.write("         <span class=\"float-right\">\r\n");
      out.write("         <a href=\"promoUpdateForm.do?type=");
      out.print(type);
      out.write("&cp=");
      out.print(cp);
      out.write("&no=");
      out.print(board.getBoardNo());
      out.write("\" id=\"updateBtn\">수정 &nbsp;</a> \r\n");
      out.write("         </span>\r\n");
      out.write("         \r\n");
      out.write("  \t");
} else if(loginMember != null  && loginMember.getMemberGrade().equals("A") ) {
      out.write("\t\t\t\t \r\n");
      out.write("  \t\t <span class=\"float-right\" id=\"deleteBtn\">\r\n");
      out.write("\t\t\t\t 삭제</span>\r\n");
      out.write("\t\t\t\t \r\n");
      out.write("\t\t\t\t");
  if (loginMember.getMemberId().equals(memberId) ) { 
      out.write("\r\n");
      out.write("\t\t\t\t <span class=\"float-right\">|&nbsp;&nbsp;</span>\r\n");
      out.write("\t\t\t\t \r\n");
      out.write("         <span class=\"float-right\">\r\n");
      out.write("         <a href=\"promoUpdateForm.do?type=");
      out.print(type);
      out.write("&cp=");
      out.print(cp);
      out.write("&no=");
      out.print(board.getBoardNo());
      out.write("\" id=\"updateBtn\">수정 &nbsp;</a> \r\n");
      out.write("         </span>\r\n");
      out.write("         \r\n");
      out.write("         \t");
} } 
      out.write("\r\n");
      out.write("\t\t\t</p>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"promo_area\">\r\n");
      out.write("\t\t\t\t<div id=\"promo_thum\">\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("  \t\t\t");
 if(fList != null){ 
      out.write("\r\n");
      out.write("                    <div class=\"boardImgArea\">\r\n");
      out.write("                     ");
 
	                   		String src = null;
                   			for(int i=0; i<1 ; i++) {
                   			 for(Attachment at : fList){
	                    	  if(at.getFileLevel() == i){
	                    		 src = request.getContextPath()+"/resources/uploadImages/"+at.getFileChangeName();
	                    		 
                 	   
      out.write(" \t  \r\n");
      out.write("\t                    <img src=\"");
      out.print(src);
      out.write("\" width=\"400px\">\r\n");
      out.write("\t                       \r\n");
      out.write("\t                    ");
  } } }  
      out.write("\r\n");
      out.write("\t                    </div> \r\n");
      out.write("                ");
 } 
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t</div>\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<div id=\"promo_detail\">\r\n");
      out.write("\t\t\t\t\t<table width=400>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td colspan=\"2\" height=50><h3>");
      out.print(board.getBoardTitle() );
      out.write("</h3> </td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td><b>연령</b> </td>\r\n");
      out.write("\t\t\t\t\t\t\t<td>");
      out.print(board.getSellAge() );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td><b>가격</b> </td>\r\n");
      out.write("\t\t\t\t\t\t\t<td>");
      out.print(board.getPrice());
      out.write("원</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td><b>안내사항</b></td>\r\n");
      out.write("\t\t\t\t\t\t\t<td rowspan=\"2\"> ");
      out.print(board.getSellIntro());
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<br> \r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td><b> <!--빈영역--></b></td>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t</table>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!-- Content -->\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<div id=\"board-imgArea\">\r\n");
      out.write("               ");
 if(fList != null){ 
      out.write("\r\n");
      out.write("                    <div class=\"boardImgArea\">\r\n");
      out.write("                     ");
 
	                   		String src = null;
                   			for(int i=1; i<4 ; i++) {
                   			 for(Attachment at : fList){
	                    	  if(at.getFileLevel() == i){
	                    		 src = request.getContextPath()+"/resources/uploadImages/"+at.getFileChangeName();
                 	   
      out.write(" \t  \r\n");
      out.write("\t                    \t\t\r\n");
      out.write("\t                          <img src=\"");
      out.print(src);
      out.write("\">\r\n");
      out.write("\t                       \r\n");
      out.write("\t                    ");
  } } } //여기 
      out.write("\r\n");
      out.write("\t                    </div> \r\n");
      out.write("            \r\n");
      out.write("                ");
 } 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t\t\t\t<div id=\"board-textArea\">\r\n");
      out.write("\t\t\t\t\t\t");
      out.print(board.getBoardContent() );
      out.write("<br>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<hr>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<div class=\"form-inline mb-2\">\r\n");
      out.write("\t\t\t\t\t<label class=\"input-group-addon mr-3 insert-label\">태그</label> \r\n");
      out.write("\t\t\t\t\t<input type=\"text\" class=\"productTagArea\" id=\"hashtag1\" name=\"hashtag1\" size=\"12\" placeholder=\"#\"> &nbsp;\r\n");
      out.write("\t\t\t\t\t<input type=\"text\" class=\"productTagArea\" id=\"hashtag2\" name=\"hashtag2\" size=\"12\" placeholder=\"#\"> &nbsp;\r\n");
      out.write("\t\t\t\t\t<input type=\"text\" class=\"productTagArea\" id=\"hashtag3\" name=\"hashtag3\" size=\"12\" placeholder=\"#\"> &nbsp;\r\n");
      out.write("\t\t\t\t\t<input type=\"text\" class=\"productTagArea\" id=\"hashtag4\" name=\"hashtag4\" size=\"12\" placeholder=\"#\"> &nbsp;\r\n");
      out.write("\t\t\t\t\t<input type=\"text\" class=\"productTagArea\" id=\"hashtag5\" name=\"hashtag5\" size=\"12\" placeholder=\"#\"> &nbsp;\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<hr>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<div>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("               \r\n");
      out.write("            </div>\r\n");
      out.write("            <div>\r\n");
      out.write("                <a class=\"btn btn-primary float-right\" href=\"");
      out.print(request.getContextPath());
      out.write("/community/promoList.do?type=4&cp=");
      out.print(cp);
      out.write("\">목록으로</a> \r\n");
      out.write("\t\t \t");
if(loginMember != null && loginMember.getMemberGrade().equals("G")){ 
      out.write("\r\n");
      out.write("               <span class=\"float-left\"><a href=\"#\" class=\"btn btn-primary\"  id=\"reportBtn\" data-toggle=\"modal\" data-target=\"#en-modal\">신고하기</a> &nbsp;&nbsp;</span>\r\n");
      out.write("             \t<span class=\"float-left\">   <a href=\"#\" class=\"btn btn-primary\" id=\"likeBtn\">좋아요</a> &nbsp;&nbsp;</span>\r\n");
      out.write("             ");
} 
      out.write("\r\n");
      out.write("\t\t\t<br>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\r\n");
      out.write("\t");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("    \n");

	Member tempMember = (Member)session.getAttribute("loginMember");

      out.write("\n");
      out.write("    \n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<title>커뮤니티/홍보게시판 댓글 화면</title>\n");
      out.write("\n");
      out.write("<style>\n");
      out.write("\n");
      out.write("\t\t/*댓글*/\t\n");
      out.write(".replyWrite>table {\n");
      out.write("\twidth: 90%;\n");
      out.write("\tmargin-top : 100px;\n");
      out.write("}\n");
      out.write("\n");
      out.write("#replyContentArea {\n");
      out.write("\twidth: 90%;\n");
      out.write("}\n");
      out.write("\n");
      out.write("#replyContentArea>textarea {\n");
      out.write("\tresize: none;\n");
      out.write("\twidth: 100%;\n");
      out.write("}\n");
      out.write("\n");
      out.write("#replyBtnArea {\n");
      out.write("\twidth: 100px;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".rWriter {\n");
      out.write("\tdisplay : inline-block;\n");
      out.write("\tmargin-right: 30px;\n");
      out.write("\tvertical-align: top;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".rDate {\n");
      out.write("\tdisplay : inline-block;\n");
      out.write("\tfont-size: 0.5em;\n");
      out.write("\tcolor: gray;\n");
      out.write("}\n");
      out.write("\n");
      out.write("#replyListArea {\n");
      out.write("\tlist-style-type: none;\n");
      out.write("\tmargin-top: 20px;\n");
      out.write("\tmargin-bottom: 0px;\n");
      out.write("\tpadding-left: 0px;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".rContent, .btnArea{\n");
      out.write("\tdisplay: inline-block;\n");
      out.write("\tbox-sizing: border-box;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".rContent {\n");
      out.write("\theight: 100%;\n");
      out.write("\twidth : 84.5%;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".btnArea {\n");
      out.write("\theight: 100%;\n");
      out.write("\twidth : 15%;\n");
      out.write("\ttext-align: right;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".dayText{\n");
      out.write("\ttext-align: left;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".textSize{\n");
      out.write("\tfont-size: 13px;\n");
      out.write("}\n");
      out.write("\n");
      out.write("\t\n");
      out.write("</style>\n");
      out.write("\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("\t\t\t\t<div id=\"reply-area \">\t\n");
      out.write("\t\t\t\t\t<!-- 댓글 작성 부분 -->\n");
      out.write("\t\t\t\t\t");
if(tempMember != null) { 
      out.write("\n");
      out.write("\t\t\t\t\t\t<div class=\"replyWrite\">\n");
      out.write("\t\t\t\t\t\t\t<table align=\"center\">\n");
      out.write("\t\t\t\t\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t\t\t\t\t<td id=\"replyContentArea\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<textArea rows=\"3\" id=\"replyContent\" maxlength=\"100\"></textArea>\n");
      out.write("\t\t\t\t\t\t\t\t\t</td>\n");
      out.write("\t\t\t\t\t\t\t\t\t<td id=\"replyBtnArea\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<button class=\"btn btn-primary\" id=\"addReply\">등록</button>\n");
      out.write("\t\t\t\t\t\t\t\t\t</td>\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t\t\t\t</table>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t");
} 
      out.write("\n");
      out.write("\t\n");
      out.write("\t\n");
      out.write("\t\t\t\t\t<!-- 댓글 출력 부분 -->\n");
      out.write("\t\t\t\t\t<div class=\"replyList pt-2\">\n");
      out.write("\t\t\t\t\t\t<ul id=\"replyListArea\">\n");
      out.write("\t\t\t\t\t\t  <li class=\"reply-row\" id=\"1\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<p class=\"rWriter\"></p> \n");
      out.write("\t\t\t\t\t\t\t\t\t<p class=\"rDate\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<br>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t\t\t</p>\n");
      out.write("\t\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t\t<p class=\"rContent\">\n");
      out.write("\t\t\t\t\t\t\t\t</p>\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"btnArea\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<button class=\"btn btn-primary\" id=\"updateReply\">수정</button>\n");
      out.write("\t\t\t\t\t\t\t\t\t<button class=\"btn btn-primary\" id=\"deleteReply\">삭제</button>\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t</li>\n");
      out.write("\t\t\t\t\t\t\t<hr> \n");
      out.write("\t\t\t\t\t\t</ul>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t\n");
      out.write("<script>\n");
      out.write("\n");

	Member tempMember2 = (Member)session.getAttribute("loginMember");
	Board tempBoard = (Board)request.getAttribute("board");

      out.write("\n");
      out.write("\tvar loginMemberId;\n");
      out.write("\t\n");
      out.write("\t");

		if(tempMember2 != null) {
      out.write("\n");
      out.write("\t\tloginMemberId = \"");
      out.print(tempMember2.getMemberId());
      out.write("\";\n");
      out.write("\t");
}
      out.write("\n");
      out.write("\t\n");
      out.write("\t$(function(){\n");
      out.write("\t\tselectReplyList(");
      out.print(tempBoard.getBoardNo());
      out.write(");\n");
      out.write("\t});\n");
      out.write("\n");
      out.write("\t\n");
      out.write("\t\n");
      out.write("\tfunction selectReplyList(boardNo){\n");
      out.write("\t\tvar url = \"");
      out.print(request.getContextPath());
      out.write("/communityReply/freeReplyList.do\";\n");
      out.write("\t\tconsole.log(boardNo);\n");
      out.write("\t\t\n");
      out.write("\t\t$.ajax({\n");
      out.write("\t\t\turl : url,\n");
      out.write("\t\t\tdata : {\"boardNo\" : boardNo},\n");
      out.write("\t\t\tdataType : \"JSON\",\n");
      out.write("\t\t\tsuccess : function(rList){\n");
      out.write("\t\t\t\tconsole.log(rList);\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\t$(\"#replyListArea\").html(\"\");\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\t$.each(rList, function(i){\n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t\t\tvar $li = $(\"<li>\").addClass(\"reply-row\");\n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t\t\tvar $div = $(\"<div>\").addClass(\"dayText\");\n");
      out.write("\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\tvar $rWriter = $(\"<a>\")\n");
      out.write("\t\t\t\t\t\t.addClass(\"rWriter\").html(rList[i].memberNickName);\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\t\tvar $rDate = $(\"<p>\").addClass(\"rDate textSize\")\n");
      out.write("\t\t\t\t\t\t.html(\"작성일 : \" + rList[i].replyCreateDate  + \"<br>\" + \n");
      out.write("\t\t\t\t\t\t\"마지막 수정일 : \" + rList[i].replyModifyDate);\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\t\t$div.append($rWriter, $rDate);\n");
      out.write("\t\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\tvar $rContent = $(\"<p>\").addClass(\"rContent dayText\")\n");
      out.write("\t\t\t\t\t\t\t\t\t.html(rList[i].replyContent);\n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t\t\tvar $btnArea = $(\"<div>\").addClass(\"btnArea\");\n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t\t\tif(rList[i].memberId == loginMemberId){\n");
      out.write("\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\tvar $updateReply = $(\"<button>\").addClass(\n");
      out.write("\t\t\t\t\t\t\t\t\"btn btn-primary btn-sm ml\")\n");
      out.write("\t\t\t\t\t\t\t\t\t.text(\"수정\").attr(\"onclick\", \n");
      out.write("\t\t\t\t\t\t\t\t\t\t\"updateFormReply(this, \"+rList[i].replyNo+\")\");\n");
      out.write("\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\tvar $deleteReply = $(\"<button>\").addClass(\n");
      out.write("\t\t\t\t\t\t\"btn btn-primary btn-sm ml\")\n");
      out.write("\t\t\t\t\t\t\t.text(\"삭제\").attr(\"onclick\", \n");
      out.write("\t\t\t\t\t\t\t\t\"deleteReply(\"+rList[i].replyNo+\")\");\n");
      out.write("\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t$btnArea.append($updateReply, $deleteReply);\n");
      out.write("\t\t\t\t\t}\n");
      out.write("\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\tvar $hr = $(\"<hr>\");\n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t\t\t$li.append($div, $rContent, $btnArea);\n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t\t\t$(\"#replyListArea\").append($li, $hr);\n");
      out.write("\t\t\t\t});\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t}, error : function(){\n");
      out.write("\t\t\t\tconsole.log(\"ajax 통신 실패\");\n");
      out.write("\t\t\t}\n");
      out.write("\t\t});\n");
      out.write("\t}\n");
      out.write("\t\n");
      out.write("\n");
      out.write("\t\n");
      out.write("\t$(\"#addReply\").on(\"click\", function(){\n");
      out.write("\t\t\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t// 작성된 댓글 내용을 얻어옴\n");
      out.write("\t\t\tvar replyContent = $(\"#replyContent\").val();\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t// 댓글이 작성되어 있는지 유효성 검사 진행\n");
      out.write("\t\t\tif(replyContent.trim().length == 0){\n");
      out.write("\t\t\t\talert(\"댓글 작성 후 클릭해주세요.\");\n");
      out.write("\t\t\t\t$(\"#replyContent\").focus();\n");
      out.write("\t\t\t}else{\n");
      out.write("\t\t\t\t// 로그인도 되어있고, 댓글도 작성되어 있는 경우\n");
      out.write("\t\t\t\tvar url = \"");
      out.print(request.getContextPath());
      out.write("/communityReply/freeInsertReply.do\";\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\t// 작성자 : 전역변수 loginMemberId 사용\n");
      out.write("\t\t\t\t// 글번호\n");
      out.write("\t\t\t\tvar boardNo = ");
      out.print(tempBoard.getBoardNo());
      out.write("\n");
      out.write("\t\t\t\t$.ajax({\n");
      out.write("\t\t\t\t\turl : url,\n");
      out.write("\t\t\t\t\ttype : \"POST\",\n");
      out.write("\t\t\t\t\tdata : {\"memberId\" : loginMemberId, \n");
      out.write("\t\t\t\t\t\t\t\"boardNo\" : boardNo,\n");
      out.write("\t\t\t\t\t\t\t\"replyContent\" : replyContent},\n");
      out.write("\t\t\t\t\tsuccess : function(result){\n");
      out.write("\t\t\t\t\t\talert(result);\n");
      out.write("\t\t\t\t\t\t$(\"#replyContent\").val(\"\");\n");
      out.write("\t\t\t\t\t\t// 삽입된 내용을 화면에서 지움\n");
      out.write("\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t// 갱신된 DB 내용을 다시 조회하여 화면 댓글 목록을 갱신함\n");
      out.write("\t\t\t\t\t\tselectReplyList(boardNo);\n");
      out.write("\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t}, error : function(){\n");
      out.write("\t\t\t\t\t\tconsole.log(\"ajax 통신 실패\");\n");
      out.write("\t\t\t\t\t}\n");
      out.write("\t\t\t\t});\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t}\n");
      out.write("\n");
      out.write("\t});\n");
      out.write("\t\n");
      out.write("\tfunction deleteReply(replyNo){\n");
      out.write("\t\t\n");
      out.write("\t\tif(confirm(\"해당 댓글을 삭제하시겠습니까?\")){\n");
      out.write("\t\t\t\n");
      out.write("\t\t\tvar url = \"");
      out.print(request.getContextPath());
      out.write("/communityReply/freeDeleteReply.do\";\n");
      out.write("\t\t\tvar boardNo = ");
      out.print(tempBoard.getBoardNo());
      out.write("\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t$.ajax({\n");
      out.write("\t\t\t\turl : url,\n");
      out.write("\t\t\t\ttype : \"POST\",\n");
      out.write("\t\t\t\tdata : {\"replyNo\" : replyNo},\n");
      out.write("\t\t\t\tsuccess : function(result){\n");
      out.write("\t\t\t\t\talert(result);\n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t\t\t// 삭제 성공 시\n");
      out.write("\t\t\t\t\t// 댓글 목록을 다시 작성\n");
      out.write("\t\t\t\t\tselectReplyList(boardNo);\n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t\t}, error : function(){\n");
      out.write("\t\t\t\t\tconsole.log(\"ajax 통신 실패\");\n");
      out.write("\t\t\t\t}\n");
      out.write("\t\t\t});\n");
      out.write("\t\t}\n");
      out.write("\t}\n");
      out.write("\t\n");
      out.write("\tfunction updateFormReply(e,replyNo){\n");
      out.write("\n");
      out.write("\t\t   var content = $(e).parent().prev().html();\n");
      out.write("\n");
      out.write("\t\t   $(e).parent().prev().html('');\n");
      out.write("\n");
      out.write("\t\t   $(e).parent().prev().append(\"<textarea style='width:100%; resize:none;'>\"+content+\"</textarea>\");\n");
      out.write("\t\t   \n");
      out.write("\t\t   var parent = $(e).parent();\n");
      out.write("\n");
      out.write("\t\t   $(e).parent().html('');  \n");
      out.write("\t\t   MBtn = $('<button style=\"float: left; margin-left: 10px; margin-bottom: 10px;\">').addClass('btn btn-primary').text('수정').attr('onclick', 'updateReply(this, '+replyNo+')');\n");
      out.write("\t\t   \n");
      out.write("\t\t   parent.append(MBtn);\n");
      out.write("\t\t   \n");
      out.write("\t\t}\n");
      out.write("\t   \n");
      out.write("\tfunction updateReply(e,replyNo) {\n");
      out.write("\t\t   var url = '");
      out.print(request.getContextPath());
      out.write("/communityReply/freeUpdateReply.do';\n");
      out.write("\t\t\tvar boardNo = ");
      out.print(tempBoard.getBoardNo());
      out.write("\n");
      out.write("\t\t   \n");
      out.write("\t\t   var content = $(e).parent().prev().children('textarea').val();\n");
      out.write("\t\t   console.log(content);\n");
      out.write("\t\t   \n");
      out.write("\t\t   $.ajax({\n");
      out.write("\t\t      url : url,\n");
      out.write("\t\t      data : {'replyNo':replyNo,\n");
      out.write("\t\t            'replyContent':content},\n");
      out.write("\t\t      success : function(result){\n");
      out.write("\t\t         swal(result);\n");
      out.write("\t\t         \n");
      out.write("\t\t         selectReplyList(boardNo);\n");
      out.write("\t\t         \n");
      out.write("\t\t      }, error : function(){\n");
      out.write("\t\t         console.log('ajax통신 실패');\n");
      out.write("\t\t      }\n");
      out.write("\t\t      \n");
      out.write("\t\t   });\n");
      out.write("\t\t}\n");
      out.write("\n");
      out.write("\n");
      out.write("\t\t\n");
      out.write("\n");
      out.write("\n");
      out.write("</script>\t\t\t\t\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<style>\r\n");
      out.write("\t#footer {\r\n");
      out.write("\t\twidth: 100%;\r\n");
      out.write("\t\tbackground-color: lightgray;\r\n");
      out.write("\t\tpadding: 20px;\r\n");
      out.write("\t\tmargin-top : 15px;\r\n");
      out.write("\t}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div class=\"row\">\r\n");
      out.write("\t\t<div class=\"col-md-12\">\r\n");
      out.write("\t\t  <p id=\"footer\">KH정보교육원 A클래스 - 세미 프로젝트 육아를도와조(5조) 슬기로운 육아생활</p>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t        <!-- Modal -->\r\n");
      out.write("           <div class=\"modal fade\" id=\"en-modal\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"exampleModalLabel\" aria-hidden=\"true\">\r\n");
      out.write("             <div class=\"modal-dialog\">\r\n");
      out.write("                 <div class=\"modal-content\" style=\"width: 400px;\">\r\n");
      out.write("                 <div class=\"modal-header\">\r\n");
      out.write("                     <h5 class=\"modal-title\" id=\"exampleModalLabel\">신고하기</h5>\r\n");
      out.write("                     <button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-label=\"Close\">\r\n");
      out.write("                     <span aria-hidden=\"true\">&times;</span>\r\n");
      out.write("                     </button>\r\n");
      out.write("                 </div>\r\n");
      out.write("                 <div class=\"modal-body\">\r\n");
      out.write("                     <form action=\"");
      out.print(request.getContextPath());
      out.write("/adminPage/reportInsert.do\" id=\"information-en\" method=\"POST\">\r\n");
      out.write("                        <input type=\"hidden\" name=\"type\" value=\"");
      out.print(type);
      out.write("\">\r\n");
      out.write("                        <input type=\"hidden\" name=\"reportType\" value=\"reportType\">\r\n");
      out.write("                        <input type=\"hidden\" name=\"cp\" value=\"");
      out.print(cp );
      out.write("\">\r\n");
      out.write("                        <input type=\"hidden\" name=\"boardNo\" value=\"");
      out.print(board.getBoardNo());
      out.write("\">                     \r\n");
      out.write("                    \r\n");
      out.write("                         <input type=\"radio\" name=\"report\" value=\"1\" class=\"input-wid\" > 성적인 콘텐츠<br> <br>\r\n");
      out.write("                         <input type=\"radio\" name=\"report\" value=\"2\" class=\"input-wid\" > 폭력적 콘텐츠 <br><br>\r\n");
      out.write("                         <input type=\"radio\" name=\"report\" value=\"3\" class=\"input-wid\" > 광고 <br><br>\r\n");
      out.write("                         <input type=\"radio\" name=\"report\" value=\"4\" class=\"input-wid\" > 유해한 콘텐츠 <br><br>\r\n");
      out.write("                         <input type=\"radio\" name=\"report\" value=\"5\" class=\"input-wid\" > 아동 학대 <br><br>\r\n");
      out.write("                         <input type=\"radio\" name=\"report\" value=\"6\" class=\"input-wid\" > 테러 조장 <br><br>\r\n");
      out.write("                         <input type=\"radio\" name=\"report\" value=\"7\" class=\"input-wid\" > 스팸 콘텐츠 <br><br>\r\n");
      out.write("                         <input type=\"radio\" name=\"report\" value=\"8\" class=\"input-wid\" > 권리 침해 <br><br>\r\n");
      out.write("                        \r\n");
      out.write("                         <div class=\"modal-footer\" style=\"clear: both;\">\r\n");
      out.write("                             <button type=\"button\" class=\"btn btn-secondary\" data-dismiss=\"modal\">취소</button>\r\n");
      out.write("                             <button type=\"submit\" class=\"btn btn-primary\" id=\"inforBtn\">요청</button>\r\n");
      out.write("                         </div>\r\n");
      out.write("                       \r\n");
      out.write("                     </form>\r\n");
      out.write("                 </div>\r\n");
      out.write("                 </div>\r\n");
      out.write("             </div>\r\n");
      out.write("         </div> \r\n");
      out.write("\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\t$(\"#deleteBtn\").on(\"click\",function(){\r\n");
      out.write("\t\t\tif(confirm(\"정말 삭제 하시겠습니까?\")) location.href = \"promoDelete.do?type=");
      out.print(type);
      out.write("&cp=");
      out.print(cp);
      out.write("&no=");
      out.print(board.getBoardNo());
      out.write("\";\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t // 글자수 제한\r\n");
      out.write("\t     \r\n");
      out.write("        $(\"textarea\").on(\"input\", function() {\r\n");
      out.write("\t        \r\n");
      out.write("\t        var inputLength = $(this).val().length;\r\n");
      out.write("\t  \r\n");
      out.write("\t        $(\"#counter\").text(inputLength);\r\n");
      out.write("\t  \r\n");
      out.write("\t        if(inputLength - 150 < 0) {\r\n");
      out.write("\t          $(\"#counter\").css(\"color\", \"black\");\r\n");
      out.write("\t        } else {\r\n");
      out.write("\t          $(\"#counter\").css(\"color\", \"red\");\r\n");
      out.write("\t        }\r\n");
      out.write("\t        \r\n");
      out.write("\t        if(inputLength > 150){\r\n");
      out.write("\t     \t   alert(\"최대 150자까지 입력 가능합니다.\");\t        \t   \r\n");
      out.write("\t        }\r\n");
      out.write("\t      });\r\n");
      out.write("     \r\n");
      out.write("     // 좋아요기능\r\n");
      out.write("\t    var no = \"");
      out.print(boardNo);
      out.write("\";\r\n");
      out.write("\t    var type = \"");
      out.print(type);
      out.write("\";\r\n");
      out.write("\t    \r\n");
      out.write("\t    $(\"#likeBtn\").on(\"click\", function() {\r\n");
      out.write("\t    \t$.ajax({\r\n");
      out.write("\t    \t\turl : \"updateLike.do\",\r\n");
      out.write("\t    \t\tdata : {\"no\" : no, \"type\" : type},\r\n");
      out.write("\t    \t\tsuccess : function(result) {\r\n");
      out.write("\t    \t\t\tif(result) {\r\n");
      out.write("\t    \t\t\t\tswal(\"해당 게시글에 좋아요를 눌렀습니다.\");\r\n");
      out.write("\t    \t\t\t\t$(\"#likeBtn\").prop(\"disabled\", true);\r\n");
      out.write("\t    \t\t\t\t\r\n");
      out.write("\t    \t\t\t}  else {\r\n");
      out.write("\t    \t\t\t\tswal(\"좋아요 클릭 과정 중 오류 발생\");\r\n");
      out.write("\t    \t\t\t}\r\n");
      out.write("\t    \t\t}, error : function() {\r\n");
      out.write("\t    \t\t\tconsole.log(\"ajax 통신 실패\");\r\n");
      out.write("\t    \t\t}\r\n");
      out.write("\t    \t});\r\n");
      out.write("\t    });\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t // 태그 split으로 화면에 출력\r\n");
      out.write("\t      var jbString = \"");
      out.print(board.getHashtag());
      out.write("\";\r\n");
      out.write("\t\t\t  var jbSplit = jbString.split(',');\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t  var hashtag = [];\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tfor (var i=1; i<6 ; i++ ){\r\n");
      out.write("\t\t\t\thashtag[i] = document.getElementById(\"hashtag\"+i);\r\n");
      out.write("\t\t\t  hashtag[i].value+=\"#\"+jbSplit[i-1] ;\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t// 로그인 유효성 검사\r\n");
      out.write("\t\t\t// -> 아이디, 비밀번호 중 하나라도 입력되지 않으면 form태그 기본 이벤트를 제거한다\r\n");
      out.write("\t\t\tfunction loginValidate(){\r\n");
      out.write("\t\t\t\tif ($(\"#memberId\").val().trim() == \"\"){\r\n");
      out.write("\t\t\t\t\talert(\"아이디를 입력해 주세요.\");\r\n");
      out.write("\t\t\t\t\t$(\"#memberId\").focus();\r\n");
      out.write("\t\t\t\t\treturn false; // 기본 이벤트 제거 \r\n");
      out.write("\t\t\t\t} \r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tif ($(\"#memberPwd\").val().trim() == \"\"){\r\n");
      out.write("\t\t\t\t\talert(\"비밀번를 입력해 주세요.\");\r\n");
      out.write("\t\t\t\t\t$(\"#memberPwd\").focus();\r\n");
      out.write("\t\t\t\t\treturn false; // 기본 이벤트 제거 \r\n");
      out.write("\t\t\t\t} \r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\treturn true; // if문에 안 걸렸으면 기본 이벤트 실행해라 라는 뜻\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t  \r\n");
      out.write("\t</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
