/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.56
 * Generated at: 2020-08-05 00:27:31 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.member;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.kh.baby.member.model.vo.Member;
import com.kh.baby.member.model.vo.Member;
import com.kh.baby.member.model.vo.General;
import com.kh.baby.member.model.vo.Seller;
import com.kh.baby.member.model.vo.Member;
import com.kh.baby.member.model.vo.General;

public final class signOutForm_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(5);
    _jspx_dependants.put("/WEB-INF/views/member/../common/header.jsp", Long.valueOf(1596541143530L));
    _jspx_dependants.put("/WEB-INF/views/member/../common/aside.jsp", Long.valueOf(1596584490494L));
    _jspx_dependants.put("/WEB-INF/views/member/../common/footer.jsp", Long.valueOf(1595827282993L));
    _jspx_dependants.put("/WEB-INF/views/mypage/mypage_aside.jsp", Long.valueOf(1596541143522L));
    _jspx_dependants.put("/WEB-INF/views/adminPage/adminAside.jsp", Long.valueOf(1596411224776L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.kh.baby.member.model.vo.General");
    _jspx_imports_classes.add("com.kh.baby.member.model.vo.Seller");
    _jspx_imports_classes.add("com.kh.baby.member.model.vo.Member");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<title>회원탈퇴</title>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\t<div class=\"container-fluid\">\n");
      out.write("\t");
      out.write("\r\n");
      out.write("\r\n");

	Member loginMemberH = (Member)session.getAttribute("loginMember");

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("<head>\r\n");
      out.write("  <meta charset=\"utf-8\">\r\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("  \r\n");
      out.write("  <!-- Bootstrap core CSS -->\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css\">\r\n");
      out.write("\r\n");
      out.write("\t<style>\r\n");
      out.write("\t    /* 전체 사이즈 지정 */\r\n");
      out.write("        .container-fluid {\r\n");
      out.write("            width: 1800px;\r\n");
      out.write("            /* height: 1000px; */\r\n");
      out.write("        }\r\n");
      out.write("        div {\r\n");
      out.write("            /* border: 1px solid black; */\r\n");
      out.write("            text-align: center;\r\n");
      out.write("        }\r\n");
      out.write("        /* header 스타일 */\r\n");
      out.write("        #header {\r\n");
      out.write("        \theight: 160px;\r\n");
      out.write("        }\r\n");
      out.write("        #header img {\r\n");
      out.write("        \theight: 100%;\r\n");
      out.write("        }\r\n");
      out.write("        /* navi 스타일 */\r\n");
      out.write("        .nav {\r\n");
      out.write("            width: 100%;\r\n");
      out.write("        }\r\n");
      out.write("        .nav-item { /* ul > li*/\r\n");
      out.write("            width: 20%;\r\n");
      out.write("            background-color: rgb(186, 234, 253);\r\n");
      out.write("        }\r\n");
      out.write("        .nav li>ul {\r\n");
      out.write("        position: absolute;\r\n");
      out.write("        width: 100%;\r\n");
      out.write("\t\tz-index: 1;\r\n");
      out.write("        background-color: rgb(217, 244, 255);\r\n");
      out.write("\r\n");
      out.write("        list-style-type: none;\r\n");
      out.write("\r\n");
      out.write("        margin: 0;\r\n");
      out.write("        padding: 0;\r\n");
      out.write("\r\n");
      out.write("        opacity: 0;\r\n");
      out.write("        }\r\n");
      out.write("        .nav ul>li>a {\r\n");
      out.write("            opacity: 0;\r\n");
      out.write("        }\r\n");
      out.write("        .nav ul>li {\r\n");
      out.write("            height: 0;\r\n");
      out.write("            line-height: 0;\r\n");
      out.write("        }\r\n");
      out.write("        .nav>li:hover ul, .nav>li:hover ul a {\r\n");
      out.write("            opacity: 1;\r\n");
      out.write("        }\r\n");
      out.write("        .nav li:hover ul li {\r\n");
      out.write("            height: 50px;\r\n");
      out.write("            line-height: 50px;\r\n");
      out.write("        }\r\n");
      out.write("        .nav li ul {\r\n");
      out.write("            transition-duration: 0.4s;\r\n");
      out.write("        }\r\n");
      out.write("\t</style>\r\n");
      out.write("\t<!-- sweetalert : alert창을 꾸밀 수 있게 해주는 라이브러리 https://sweetalert.js.org/ -->\r\n");
      out.write("    <script src=\"https://unpkg.com/sweetalert/dist/sweetalert.min.js\"></script>\r\n");
      out.write("\t\t<script>\r\n");
      out.write("\t\t/**** 이전 페이지에서 전달받은 내용을 alert 창으로 표시하기 ****/\r\n");
      out.write("\t\t");
 
			String msg = (String)(request.getSession().getAttribute("msg"));
			String status = (String)(request.getSession().getAttribute("status"));
			String text = (String)(request.getSession().getAttribute("text"));
		
      out.write("\r\n");
      out.write("\t\t");
 if(msg != null) { 
      out.write("\r\n");
      out.write("\t\t\tswal({\r\n");
      out.write("\t\t\t\ticon : \"");
      out.print(status);
      out.write("\",\r\n");
      out.write("\t\t\t\ttitle : \"");
      out.print(msg);
      out.write("\",\r\n");
      out.write("\t\t\t\ttext : \"");
      out.print(text != null ? text : "");
      out.write("\"\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t");
 // Session에 존재하는 특정 키 값의 속성 제거
			session.removeAttribute("msg"); // session = request.getSession()
			session.removeAttribute("status");
			session.removeAttribute("text");
		} 
      out.write("\r\n");
      out.write("\t\t</script>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("            <div class=\"col-md-12\" id=\"header\">\r\n");
      out.write("              <a href=\"");
      out.print(request.getContextPath());
      out.write("\"><img src=\"");
      out.print(request.getContextPath());
      out.write("/resources/아기.PNG\"></a>\r\n");
      out.write("              <a href=\"");
      out.print(request.getContextPath());
      out.write("\"><img src=\"");
      out.print(request.getContextPath());
      out.write("/resources/로고.png\"></a>\r\n");
      out.write("              <a href=\"");
      out.print(request.getContextPath());
      out.write("\"><img src=\"");
      out.print(request.getContextPath());
      out.write("/resources/아기2.PNG\"></a>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("            <div class=\"col-md-12\">\r\n");
      out.write("                <ul class=\"nav nav-pills nav-justified\">\r\n");
      out.write("                  <li class=\"nav-item\">\r\n");
      out.write("                    <a class=\"nav-link active\" href=\"");
      out.print(request.getContextPath());
      out.write("\">MAIN</a>\r\n");
      out.write("                  </li>\r\n");
      out.write("                  \r\n");
      out.write("                  <li class=\"nav-item\">\r\n");
      out.write("                    <a class=\"nav-link\" href=\"#\">ABOUT</a>\r\n");
      out.write("                  </li>\r\n");
      out.write("                  \r\n");
      out.write("                  <li class=\"nav-item dropdown\">\r\n");
      out.write("                    <a class=\"nav-link dropdown-toggle\" data-toggle=\"dropdown\" href=\"#\" role=\"button\" aria-haspopup=\"true\" aria-expanded=\"false\">INFORMATION</a>\r\n");
      out.write("                      <ul>\r\n");
      out.write("                        <li><a class=\"dropdown-item text-primary\" href=\"");
      out.print(request.getContextPath());
      out.write("/board/hospitalForm.do?type=1&cp=1\">지역별 병원 정보</a></li>\r\n");
      out.write("                        <li><a class=\"dropdown-item text-primary\" href=\"");
      out.print(request.getContextPath());
      out.write("/board/knowledgeForm.do?type=2&cp=1&age=0\">아이 연령대별 상식</a></li>\r\n");
      out.write("                      </ul>\r\n");
      out.write("                  </li>\r\n");
      out.write("                  \r\n");
      out.write("                  <li class=\"nav-item dropdown\">\r\n");
      out.write("                    <a class=\"nav-link dropdown-toggle\" data-toggle=\"dropdown\" href=\"#\" role=\"button\" aria-haspopup=\"true\" aria-expanded=\"false\">COMMUNITY</a>\r\n");
      out.write("                      <ul>\r\n");
      out.write("                        <li><a class=\"dropdown-item text-primary\" href=\"");
      out.print(request.getContextPath());
      out.write("/community/freeList.do?type=3\">자유게시판</a></li>\r\n");
      out.write("                        <li><a class=\"dropdown-item text-primary\" href=\"");
      out.print(request.getContextPath());
      out.write("/community/promoList.do?type=4\">홍보게시판</a></li>\r\n");
      out.write("                      </ul>\r\n");
      out.write("                  </li>\r\n");
      out.write("                  \r\n");
      out.write("                  <li class=\"nav-item dropdown\">\r\n");
      out.write("                    <a class=\"nav-link dropdown-toggle\" data-toggle=\"dropdown\" href=\"");
      out.print(request.getContextPath());
      out.write("/mypage/babyInfoForm.do\" role=\"button\" aria-haspopup=\"true\" aria-expanded=\"false\">MY PAGE</a>\r\n");
      out.write("                    <ul>\r\n");
      out.write("                    \t");
 
                    		String url = request.getContextPath() + "/mypage/babyInfoForm.do?memberNo=";
                    		if(loginMemberH != null) url += loginMemberH.getMemberNo();
                    	
      out.write("\r\n");
      out.write("                    \t");
if(loginMemberH != null) {
      out.write("\r\n");
      out.write("                    \t\t");
if(loginMemberH.getMemberGrade().equals("G")) { 
      out.write("\r\n");
      out.write("\t                        <li><a class=\"dropdown-item text-primary\" href=\"");
      out.print(url);
      out.write("\">우리 아이 정보</a></li>\r\n");
      out.write("\t                        <li><a class=\"dropdown-item text-primary\" href=\"");
      out.print(request.getContextPath());
      out.write("/mypage/babyDiaryForm.do\">육아 일기</a></li>\r\n");
      out.write("\t                        <li><a class=\"dropdown-item text-primary\" href=\"");
      out.print(request.getContextPath());
      out.write("/mypage/myBoardList.do?cp=1\">작성한 글</a></li>\r\n");
      out.write("\t                        <li><a class=\"dropdown-item text-primary\" href=\"");
      out.print(request.getContextPath());
      out.write("/member/updateMemberForm.do\">개인 정보 관리</a></li>\r\n");
      out.write("                        ");
 } else if(loginMemberH.getMemberGrade().equals("S")) { 
      out.write("\r\n");
      out.write("\t                       \t<li><a class=\"dropdown-item text-primary\" href=\"");
      out.print(request.getContextPath());
      out.write("/member/myCompanyInfoForm.do\">우리 회사 정보</a></li>\r\n");
      out.write("\t                        <li><a class=\"dropdown-item text-primary\" href=\"");
      out.print(request.getContextPath());
      out.write("/mypage/myBoardList.do?cp=1\">작성한 글</a></li>\r\n");
      out.write("\t                        <li><a class=\"dropdown-item text-primary\" href=\"");
      out.print(request.getContextPath());
      out.write("/member/updateSellerForm.do\">개인 정보 관리</a></li>\r\n");
      out.write("                        ");
 } else if(loginMemberH.getMemberGrade().equals("A")) { 
      out.write("\r\n");
      out.write("\t                        <li><a class=\"dropdown-item text-primary\" href=\"");
      out.print(request.getContextPath());
      out.write("/adminPage/reportBoard.do\">신고게시판 </a></li>\r\n");
      out.write("\t                        <li><a class=\"dropdown-item text-primary\" href=\"");
      out.print(request.getContextPath());
      out.write("/adminPage/requestBoard.do\">요청게시판</a></li>\r\n");
      out.write("\t                        <li><a class=\"dropdown-item text-primary\" href=\"");
      out.print(request.getContextPath());
      out.write("/adminPage/noticeBoard.do\">공지사항</a></li>\r\n");
      out.write("\t                        <li><a class=\"dropdown-item text-primary\" href=\"");
      out.print(request.getContextPath());
      out.write("/adminPage/memberView.do\">회원 정보 조회</a></li>\r\n");
      out.write("\t                        <li><a class=\"dropdown-item text-primary\" href=\"");
      out.print(request.getContextPath());
      out.write("/adminPage/adminWrite.do\">글쓰기</a></li>\r\n");
      out.write("                        ");
 } }else {
      out.write("\r\n");
      out.write("                        ");
 } 
      out.write("\r\n");
      out.write("                    </ul>\r\n");
      out.write("                  </li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("\t<script>\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t$(\"a[href='#']\").on(\"click\", function(e){\r\n");
      out.write("\t\te.preventeDefault(); \r\n");
      out.write("\t\t// href 속성값이 #인 a태그를 클릭한 경우 기본 이벤트를 제거하는 자바스크립트 코드 입니다.\r\n");
      out.write("\t\t// a태그 기본이벤트 : href 속성에 작성된 주소로 요청보내기\r\n");
      out.write("\t});\r\n");
      out.write("\t</script>\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- Bootstrap core JS -->\r\n");
      out.write("\t<script src=\"https://code.jquery.com/jquery-3.5.1.min.js\"></script>\r\n");
      out.write("\t<script src=\"https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js\" integrity=\"sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("\t<script src=\"https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js\" integrity=\"sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
      out.write("\n");
      out.write("\n");
      out.write("\t<div class=\"row\" id=\"content\">\n");
      out.write("  ");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

   Member loginMember = (Member)session.getAttribute("loginMember");
    General loginGeneral = (General)session.getAttribute("loginGeneral");
    Seller loginSeller = (Seller)session.getAttribute("loginSeller");
      
    String babyGender = "";
    if(loginGeneral != null) {
       if(loginGeneral.getKidsHeight() != 0) {
         if(loginGeneral.getKidsGender().equals("f")) {
            babyGender = "공주님";
         } else {
            babyGender = "왕자님";
         }
       }
    }
      
   boolean isSave = false;
   String saveId = "";

   Cookie[] cookies = request.getCookies();

   if (cookies != null) {
      for (Cookie c : cookies) {
         if ("saveId".equals(c.getName())) {
            saveId = c.getValue();
            isSave = true;
         }
      }
   }

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<style>\r\n");
      out.write("/* aside 스타일 */\r\n");
      out.write("#aside {\r\n");
      out.write("   width: 20%;\r\n");
      out.write("   padding: 0 15px 0 15px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#login{\r\n");
      out.write("   width: 100%\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#login_btn {\r\n");
      out.write("   margin: 5px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".form-signin {\r\n");
      out.write("   background-color: lightgray;\r\n");
      out.write("   width: 100%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".form-signin>* {\r\n");
      out.write("   display: inline-block;\r\n");
      out.write("   margin: 10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#mypage {\r\n");
      out.write("   width: 100%;\r\n");
      out.write("   margin: 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#aside_menu {\r\n");
      out.write("       margin-top: 20px;\r\n");
      out.write("       margin-bottom: 20px;\r\n");
      out.write("       text-align: left;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* 테이블 스타일 지정 */\r\n");
      out.write("#member_info{\r\n");
      out.write("   width: 100%;\r\n");
      out.write("   margin: 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#member_info * {\r\n");
      out.write("   border: 1px solid white;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#member_info th {\r\n");
      out.write("   width: 80px;\r\n");
      out.write("}\r\n");
      out.write("#member_info td {\r\n");
      out.write("   width: 250px;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("   <div id=\"aside\">\r\n");
      out.write("      <div id=\"aside_login\">\r\n");
      out.write("         ");

            if (loginMember == null) {
         
      out.write("\r\n");
      out.write("         <form class=\"form-signin\" method=\"post\"\r\n");
      out.write("            action=\"");
      out.print(request.getContextPath());
      out.write("/member/login.do\">\r\n");
      out.write("            <table>\r\n");
      out.write("               <tr>\r\n");
      out.write("                  <th colspan=\"2\"><h1 class=\"h3 mb-3 font-weight-normal\">로그인</h1></th>\r\n");
      out.write("               </tr>\r\n");
      out.write("               <tr>\r\n");
      out.write("                  <td><input type=\"text\" name=\"inputId\" id=\"inputId\" class=\"form-control\" placeholder=\"아이디\" value=\"");
      out.print(saveId);
      out.write("\" required autofocus></td>\r\n");
      out.write("                  <td rowspan=\"2\">\r\n");
      out.write("                     <button class=\"btn btn-lg btn-primary btn-block\" type=\"submit\" id=\"login_btn\">LOGIN</button>\r\n");
      out.write("                  </td>\r\n");
      out.write("               </tr>\r\n");
      out.write("               <tr>\r\n");
      out.write("                  <td><input type=\"password\" name=\"inputPassword\" id=\"inputPassword\" class=\"form-control\" placeholder=\"비밀번호\" required></td>\r\n");
      out.write("               </tr>\r\n");
      out.write("               <tr>\r\n");
      out.write("                  <td><input type=\"checkbox\" name=\"saveId\" id=\"saveId\" ");
      out.print(isSave ? "checked" : "");
      out.write("><label for=\"saveId\">아이디 저장하기</label></td>\r\n");
      out.write("               </tr>\r\n");
      out.write("            </table>\r\n");
      out.write("\r\n");
      out.write("            <span>저희 홈페이지를<br>찾아주셔서 감사합니다. </span> <br> \r\n");
      out.write("            <a href=\"");
      out.print(request.getContextPath());
      out.write("/member/signUpSelect.do\">회원 가입</a> &nbsp;&nbsp;&nbsp;&nbsp; \r\n");
      out.write("            <a href=\"");
      out.print(request.getContextPath());
      out.write("/member/searchSelectForm.do\">ID/PWD 찾기</a>\r\n");
      out.write("         </form>\r\n");
      out.write("         ");

            } else {
         
      out.write("\r\n");
      out.write("         <div class=\"form-signin\" method=\"post\">\r\n");
      out.write("            <h3>");
      out.print(loginMember.getMemberNickname());
      out.write("님</h3>\r\n");
      out.write("            <a class=\"btn btn-primary\" href=\"");
      out.print(request.getContextPath());
      out.write("/member/logout.do\">Logout</a>\r\n");
      out.write("            ");
 if(loginMember.getMemberGrade().equals("G")) { 
      out.write("\r\n");
      out.write("                  <table id=\"member_info\">\r\n");
      out.write("                     <tr>\r\n");
      out.write("                        <th>주소</th>\r\n");
      out.write("                        <td>\r\n");
      out.write("                           ");
 if(!loginMember.getMemberAddress().equals(",,")) { 
      out.write("\r\n");
      out.write("                              ");
      out.print(loginMember.getMemberAddress());
      out.write("\r\n");
      out.write("                           ");
 } else { 
      out.write("\r\n");
      out.write("                              <a class=\"btn btn-light btn-sm\" href=\"");
      out.print(request.getContextPath());
      out.write("/mypage/updateAddressForm.do\">주소 설정하기</a>\r\n");
      out.write("                           ");
 } 
      out.write("\r\n");
      out.write("                        </td>\r\n");
      out.write("                     </tr>\r\n");
      out.write("      \r\n");
      out.write("                     <tr>\r\n");
      out.write("                        <th rowspan=\"4\">아이 정보  </th>\r\n");
      out.write("                     ");
 if(loginGeneral.getKidsHeight() != 0) {
      out.write("\r\n");
      out.write("                        <td>");
      out.print(loginGeneral.getKidsName());
      out.write("&nbsp;");
      out.print(babyGender);
      out.write("</td>\r\n");
      out.write("                     </tr>\r\n");
      out.write("                     <tr>\r\n");
      out.write("                        <td>생년월일 : ");
      out.print(loginGeneral.getKidsBirth() );
      out.write("</td>\r\n");
      out.write("                     </tr>\r\n");
      out.write("                     <tr>\r\n");
      out.write("                        <td>키 : ");
      out.print(loginGeneral.getKidsHeight() );
      out.write("cm</td>\r\n");
      out.write("                     </tr>\r\n");
      out.write("                     <tr>\r\n");
      out.write("                        <td>몸무게 : ");
      out.print(loginGeneral.getKidsWeight());
      out.write("kg</td>\r\n");
      out.write("                     ");
 } else { 
      out.write("\r\n");
      out.write("                        <td><a class=\"btn btn-light btn-sm\" href=\"");
      out.print(request.getContextPath());
      out.write("/mypage/insertBabyInfoForm.do\">아이 정보 설정하기</a></td>\r\n");
      out.write("                     ");
 } 
      out.write("\r\n");
      out.write("                     </tr>\r\n");
      out.write("                  </table>\r\n");
      out.write("                  ");
 } else if(loginMember.getMemberGrade().equals("S")) { 
      out.write("\r\n");
      out.write("                  <table id=\"member_info\">\r\n");
      out.write("                     <tr>\r\n");
      out.write("                        <th>주소</th>\r\n");
      out.write("                        <td>\r\n");
      out.write("                           ");
 if(!loginMember.getMemberAddress().equals(",,")) { 
      out.write("\r\n");
      out.write("                              ");
      out.print(loginMember.getMemberAddress());
      out.write("\r\n");
      out.write("                           ");
 } else { 
      out.write("\r\n");
      out.write("                              <a class=\"btn btn-light btn-sm\" href=\"");
      out.print(request.getContextPath());
      out.write("/mypage/updateAddressForm.do\">주소 설정하기</a>\r\n");
      out.write("                           ");
 } 
      out.write("\r\n");
      out.write("                        </td>\r\n");
      out.write("                     </tr>\r\n");
      out.write("      \r\n");
      out.write("                     <tr>\r\n");
      out.write("                        <th rowspan=\"2\">회사 정보  </th>\r\n");
      out.write("                     ");
 if(loginSeller != null) {
      out.write("\r\n");
      out.write("                        <td>사업자등록번호 : ");
      out.print(loginSeller.getCompanyNo() );
      out.write("</td>\r\n");
      out.write("                     </tr>\r\n");
      out.write("                     <tr>\r\n");
      out.write("                        <td>회사 전화번호 : ");
      out.print(loginSeller.getCompanyPhone() );
      out.write("</td>\r\n");
      out.write("                     ");
 } else { 
      out.write("\r\n");
      out.write("                        <td><a class=\"btn btn-light btn-sm\" href=\"");
      out.print(request.getContextPath());
      out.write("\">회사 정보 설정하기</a></td>\r\n");
      out.write("                     ");
 } 
      out.write("\r\n");
      out.write("                     </tr>\r\n");
      out.write("                  </table>\r\n");
      out.write("                  ");
 } else {
      out.write("\r\n");
      out.write("                     <h3>관리자 아이디로 로그인되었습니다.</h3>\r\n");
      out.write("                  ");
 } 
      out.write("\r\n");
      out.write("         </div>\r\n");
      out.write("         ");
if(loginMember.getMemberGrade().equals("G")) {
      out.write("\r\n");
      out.write("         <button type=\"button\" class=\"btn btn-secondary btn-lg\" id=\"mypage\" onclick=\"location.href='");
      out.print(request.getContextPath());
      out.write("/mypage/myBoardList.do?cp=1';\">MY PAGE</button>\r\n");
      out.write("         ");
} else if(loginMember.getMemberGrade().equals("S")) { 
      out.write("\r\n");
      out.write("         <button type=\"button\" class=\"btn btn-secondary btn-lg\" id=\"mypage\" onclick=\"location.href='");
      out.print(request.getContextPath());
      out.write("/mypage/myBoardList.do?cp=1';\">MY PAGE</button>\r\n");
      out.write("         ");
} else if(loginMember.getMemberGrade().equals("A")) {
      out.write("\r\n");
      out.write("         <button type=\"button\" class=\"btn btn-secondary btn-lg\" id=\"mypage\" onclick=\"location.href='");
      out.print(request.getContextPath());
      out.write("/adminPage/noticeBoard.do';\">MY PAGE</button>\r\n");
      out.write("         ");

            } }
         
      out.write("\r\n");
      out.write("      </div>\r\n");
      out.write("         \r\n");
      out.write("         <div id=\"aside_menu\">\r\n");
      out.write("            ");
 if(loginMember != null){ 
      out.write("\r\n");
      out.write("            ");
if(loginMember.getMemberGrade().equals("A")) {
      out.write("\r\n");
      out.write("            ");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css2?family=Cute+Font&family=Gugi&family=Poor+Story&display=swap;subset=korean\" rel=\"stylesheet\">\r\n");
      out.write("<style>\r\n");
      out.write(".adminPageSide{\r\n");
      out.write("\tfont-family: Poor Story;\r\n");
      out.write("    font-size: 23px;\r\n");
      out.write("    font-weight: bolder;\r\n");
      out.write("    color:black;\r\n");
      out.write("}\r\n");
      out.write("button{\r\n");
      out.write("  text-align: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("section{\r\n");
      out.write("  display: none;\r\n");
      out.write("  float:left;\r\n");
      out.write("}\r\n");
      out.write(".nav-item{\r\n");
      out.write("width : 100%;\r\n");
      out.write("height : 20%;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<ul class=\"nav flex-column\">\r\n");
      out.write("  <li class=\"nav-item adminPageSide\">\r\n");
      out.write("      <a id=\"report\" class=\"nav-link\" href=\"");
      out.print(request.getContextPath());
      out.write("/adminPage/reportBoard.do\">신고게시판 <span class=\"badge badge-pill badge-dark\"></span></a>\r\n");
      out.write("    </li>\r\n");
      out.write("  <li class=\"nav-item adminPageSide\">\r\n");
      out.write("    <a id=\"request\" class=\"nav-link\" href=\"");
      out.print(request.getContextPath());
      out.write("/adminPage/requestBoard.do\">요청게시판 <span class=\"badge badge-pill badge-dark\"></span>  </a>\r\n");
      out.write("  </li>\r\n");
      out.write("  <li class=\"nav-item adminPageSide\">\r\n");
      out.write("    <a class=\"nav-link\" href=\"");
      out.print(request.getContextPath());
      out.write("/adminPage/noticeBoard.do\">공지사항</a>\r\n");
      out.write("  </li>\r\n");
      out.write("  <li class=\"nav-item adminPageSide\">\r\n");
      out.write("    <a class=\"nav-link\" href=\"");
      out.print(request.getContextPath());
      out.write("/adminPage/memberView.do\">회원 정보 조회</a>\r\n");
      out.write("  </li>\r\n");
      out.write("  <li class=\"nav-item adminPageSide\">\r\n");
      out.write("    <a class=\"nav-link\" href=\"");
      out.print(request.getContextPath());
      out.write("/adminPage/adminWrite.do\">글쓰기</a>\r\n");
      out.write("  </li>\r\n");
      out.write("</ul>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("$(function(){\r\n");
      out.write("\t$.ajax({\r\n");
      out.write("\t\turl : \"");
      out.print(request.getContextPath());
      out.write("/adminPage/reportCount.do\",\r\n");
      out.write("\t\tsuccess : function(count){\r\n");
      out.write("\t\t\t$(\"#report > span\").text(count);\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t}, error : function(count){\r\n");
      out.write("\t\t\tconsole.log(\"Ajax 통신 실패\");\r\n");
      out.write("\t\t} \r\n");
      out.write("\t});\t\t\r\n");
      out.write("\t\r\n");
      out.write("\t$.ajax({\r\n");
      out.write("\t\turl : \"");
      out.print(request.getContextPath());
      out.write("/adminPage/requestCount.do\",\r\n");
      out.write("\t\tsuccess : function(count){\r\n");
      out.write("\t\t\t$(\"#request > span\").text(count);\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t}, error : function(count){\r\n");
      out.write("\t\t\tconsole.log(\"Ajax 통신 실패\");\r\n");
      out.write("\t\t} \r\n");
      out.write("\t});\t\t\r\n");
      out.write("});\r\n");
      out.write("</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("            ");
} else { 
      out.write("\r\n");
      out.write("            ");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	Member mploginMember = (Member)session.getAttribute("loginMember");
  General mploginGeneral = (General)session.getAttribute("loginGeneral"); 

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<style>\r\n");
      out.write("/* -------------------------------------------- */\r\n");
      out.write("\r\n");
      out.write("    .dropdown-toggle::after {\r\n");
      out.write("      display: block;\r\n");
      out.write("      position: absolute;\r\n");
      out.write("      top: 50%;\r\n");
      out.write("      right: 20px;\r\n");
      out.write("      transform: translateY(-50%);\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .asideCategory\r\n");
      out.write("    {\r\n");
      out.write("        text-decoration: none; color: black;\r\n");
      out.write("        display: block;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .asideCategory:hover{\r\n");
      out.write("        text-decoration: none; color: black; font-weight: bold;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("\t#aside_menu li>a{\r\n");
      out.write("\t\twidth: 100%;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t        <ul class=\"list-group\">\r\n");
      out.write("\t        ");
if(mploginMember.getMemberGrade().equals("G")) { 
      out.write("\r\n");
      out.write("\t        \t\t");
if(mploginGeneral.getKidsHeight()==0 && mploginGeneral.getKidsWeight()==0){ 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<li class=\"list-group-item\" id=\"atag1\"><a href=\"");
      out.print(request.getContextPath());
      out.write("/mypage/insertBabyInfoForm.do\" class=\"asideCategory\">우리 아이 정보</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t");
}else{ 
      out.write("\r\n");
      out.write("\t\t\t       \t\t<li class=\"list-group-item\" id=\"atag1\"><a href=\"");
      out.print(request.getContextPath());
      out.write("/mypage/babyInfoForm.do\" class=\"asideCategory\">우리 아이 정보</a></li>\r\n");
      out.write("\t\t\t       \t\t<li class=\"list-group-item\" id=\"atag2\" ><a href=\"");
      out.print(request.getContextPath());
      out.write("/mypage/babyDiaryForm.do?cp=1\" class=\"asideCategory\"\">육아일기</a></li>\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t");
 }
      out.write("\r\n");
      out.write("\t       \t");
} else { 
      out.write("\r\n");
      out.write("\t       \t\t<li class=\"list-group-item\" id=\"atag1\"><a href=\"");
      out.print(request.getContextPath());
      out.write("/member/myCompanyInfoForm.do\" class=\"asideCategory\">우리 회사 정보</a></li>\r\n");
      out.write("\t       \t");
 } 
      out.write("\r\n");
      out.write("\t       \t\t<li class=\"list-group-item\" id=\"atag3\"><a href=\"");
      out.print(request.getContextPath());
      out.write("/mypage/myBoardList.do?cp=1\" class=\"asideCategory\" >작성한 글</a></li>\r\n");
      out.write("\t\r\n");
      out.write("\t       \t\t<li class=\"list-group-item\" id=\"atag4\">\r\n");
      out.write("\t           \t\t<a href=\"#pageSubmenu\" data-toggle=\"collapse\" aria-expanded=\"false\" aria-haspopup=\"true\" class=\"asideCategory\">개인 정보 관리</a>\r\n");
      out.write("\t           \t\t<ul class=\"collapse list-unstyled\" id=\"pageSubmenu\">\r\n");
      out.write("\t               \t");
if(mploginMember.getMemberGrade().equals("G")) { 
      out.write("\r\n");
      out.write("\t               \t\t<li >\r\n");
      out.write("\t                   \t\t<a href=\"");
      out.print(request.getContextPath());
      out.write("/member/updateMemberForm.do\" class=\"asideCategory\"> - 개인 정보 수정</a> \r\n");
      out.write("\t               \t\t</li>\r\n");
      out.write("\t               \t");
} else { 
      out.write("       \r\n");
      out.write("\t               \t\t<li >\r\n");
      out.write("\t                   \t\t<a href=\"");
      out.print(request.getContextPath());
      out.write("/member/updateSellerForm.do\" class=\"asideCategory\"> - 회사 정보 수정</a> \r\n");
      out.write("\t               \t\t</li>\r\n");
      out.write("\t               \t");
 } 
      out.write("\r\n");
      out.write("\t               \t\t<li>\r\n");
      out.write("\t                   \t\t<a href=\"");
      out.print(request.getContextPath());
      out.write("/member/signOutForm.do\" class=\"asideCategory\"> - 회원 탈퇴</a>\r\n");
      out.write("\t               \t\t</li>\r\n");
      out.write("\t               \t\t<li>\r\n");
      out.write("\t                   \t\t<a href=\"");
      out.print(request.getContextPath());
      out.write("/mypage/replacePwdForm.do\" class=\"asideCategory\"> - 비밀번호 변경</a>\r\n");
      out.write("\t               \t\t</li>\r\n");
      out.write("\t           \t\t</ul>\r\n");
      out.write("\t       \t\t</li>\r\n");
      out.write("\t     \t</ul>\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\r\n");
      out.write("\t\t$(\"#atag1, #atag2, #atag3, #atag4\").on({\"mouseenter\" : function(){\r\n");
      out.write("\t\t\t$(this).css(\"backgroundColor\", \"rgb(186, 234, 253)\");\r\n");
      out.write("\t\t}, \"mouseleave\" : function(){\r\n");
      out.write("\t\t\t$(this).css(\"backgroundColor\", \"rgb(0, 0, 0, 0)\");\r\n");
      out.write("\t\t}});\r\n");
      out.write("\t\r\n");
      out.write("\t</script>\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("            ");
   } 
      out.write("\r\n");
      out.write("            ");
 } 
      out.write("\r\n");
      out.write("      </div>\r\n");
      out.write("   </div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("  \n");
      out.write("\n");
      out.write("\t\t\t<div class=\"col-sm-offset-2 col-sm-5\" style=\"margin: auto;\">\n");
      out.write("\n");
      out.write("\t\t\t\t<h3>회원탈퇴</h3>\n");
      out.write("\t\t\t\t<div class=\"bg-white rounded shadow-sm container p-3\">\n");
      out.write("\t\t\t\t\t<form method=\"POST\" action=\"updateStatus.do\" onsubmit=\"return validate();\" \n");
      out.write("\t\t\t\t\t\tclass=\"form-horizontal\" role=\"form\">\n");
      out.write("\t\t\t\t\t\t<!-- 아이디 -->\n");
      out.write("\t\t\t\t\t\t<div class=\"row mb-3 form-row\">\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-md-3\">\n");
      out.write("\t\t\t\t\t\t\t\t<h6>아이디</h6>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-md-6\">\n");
      out.write("\t\t\t\t\t\t\t\t<h5 id=\"id\">");
      out.print(loginMember.getMemberId());
      out.write("</h5>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t<!-- 비밀번호 -->\n");
      out.write("\t\t\t\t\t\t<div class=\"row mb-3 form-row\">\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-md-3\">\n");
      out.write("\t\t\t\t\t\t\t\t<h6>비밀번호</h6>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-md-6\">\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"password\" class=\"form-control\" id=\"currentPwd\"\n");
      out.write("\t\t\t\t\t\t\t\t\tname=\"currentPwd\">\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t<hr>\n");
      out.write("\t\t\t\t\t\t<div class=\"panel panel-default\">\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t<div class=\"panel-body\">\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"form-group pull-left\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<label class=\"control-label\"> 회원 탈퇴 약관 </label>\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"col-xs-12\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<textarea class=\"form-control\" readonly rows=\"10\" cols=\"100\">\n");
      out.write("제1조\n");
      out.write("이 약관은 샘플 약관입니다.\n");
      out.write("\n");
      out.write("① 약관 내용 1\n");
      out.write("\n");
      out.write("② 약관 내용 2\n");
      out.write("\n");
      out.write("③ 약관 내용 3\n");
      out.write("\n");
      out.write("④ 약관 내용 4\n");
      out.write("\n");
      out.write("\n");
      out.write("제2조\n");
      out.write("이 약관은 샘플 약관입니다.\n");
      out.write("\n");
      out.write("① 약관 내용 1\n");
      out.write("\n");
      out.write("② 약관 내용 2\n");
      out.write("\n");
      out.write("③ 약관 내용 3\n");
      out.write("\n");
      out.write("④ 약관 내용 4\n");
      out.write("</textarea>\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"checkbox pull-right\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"custom-checkbox\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"form-check\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"checkbox\" name=\"agree\" id=\"agree\"\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tclass=\"form-check-input custom-control-input\"> <br>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<label class=\"form-check-label custom-control-label\"\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tfor=\"agree\">위 약관에 동의합니다.</label>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t<hr class=\"mb-4\">\n");
      out.write("\t\t\t\t\t\t<button class=\"btn btn-primary btn-lg btn-block\" id=\"btn\"\n");
      out.write("\t\t\t\t\t\t\ttype=\"submit\">탈퇴</button>\n");
      out.write("\t\t\t\t\t</form>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<style>\r\n");
      out.write("\t#footer {\r\n");
      out.write("\t\twidth: 100%;\r\n");
      out.write("\t\tbackground-color: lightgray;\r\n");
      out.write("\t\tpadding: 20px;\r\n");
      out.write("\t\tmargin-top : 15px;\r\n");
      out.write("\t}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div class=\"row\">\r\n");
      out.write("\t\t<div class=\"col-md-12\">\r\n");
      out.write("\t\t  <p id=\"footer\">KH정보교육원 A클래스 - 세미 프로젝트 육아를도와조(5조) 슬기로운 육아생활</p>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\n");
      out.write("\t</div>\n");
      out.write("\n");
      out.write("\t<script>\n");
      out.write("\t\t// submit 동작\n");
      out.write("\t\tfunction validate() {\n");
      out.write("\t\t\t\n");
      out.write("\t\t\tif(!$(\"#agree\").prop(\"checked\")){\n");
      out.write("\t\t\t\talert(\"약관에 동의해 주세요.\");\n");
      out.write("\t\t\t\treturn false;\n");
      out.write("\t\t\t}else{\n");
      out.write("\t\t\t\treturn confirm(\"정말로 탈퇴하시겠습니까?\");\n");
      out.write("\t\t\t}\n");
      out.write("\t\t\n");
      out.write("\t\t\t\n");
      out.write("\t\t}\n");
      out.write("\t</script>\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
